import type { ShipmentOrderDetailRecord } from './types';

const baseShipmentOrderMock: ShipmentOrderDetailRecord = {
  orderNo: 'LCL26060200',
  hblNo: 'PTP26060186',
  mblNo: 'SPTP26060186',
  inStorageNo: 'UKSZ26060186',
  externalOrderNo: 'UUKDCG25091529',
  customerOrderNo: 'UUKDCG25091529',
  customerName: '艾力克',
  businessType: 'FBA',
  serviceScope: '全程',
  orderDate: '2026-06-26 09:33:19',
  operationOrderDate: '2026-06-25 12:00:00',
  loadingMethod: 'LCL GROUP（自拼）',
  vesselTime: 'DCG LOGISTICS UK LTD 2026-06-26 09:46:52',
  billModifyTime: 'PTP26060186,PTP26060186A,PTP26060186B',
  packageMode: 'LCL GROUP（自拼）',
  orderStats: [
    { label: '订单', value: false },
    { label: '文件', value: false },
    { label: '操作', value: false },
  ],
  enabledServices: ['订舱', '仓库内装', '报关', '清关', '派送'],
  flowTabs: [
    { label: '待审单', state: 'done' },
    { label: '审单已通过', state: 'done' },
    { label: '订舱', state: 'done' },
    { label: '放舱', state: 'current' },
    { label: '进仓', state: 'future' },
    { label: '核对进仓数据', state: 'future' },
    { label: '收集报关资料', state: 'future' },
    { label: '排柜装柜', state: 'future' },
    { label: '提柜', state: 'future' },
    { label: '补料', state: 'future' },
    { label: '开港', state: 'future' },
    { label: '还柜', state: 'future' },
    { label: '报关', state: 'future' },
    { label: '海关/码头放行', state: 'future' },
    { label: '已装船', state: 'future' },
    { label: '实际开船', state: 'future' },
  ],
  basicInfo: {
    firstRow: [
      { label: '收货地', code: 'CNYTN', value: 'YANTIAN,CHINA' },
      { label: '起运港', code: 'CNYTN', value: 'YANTIAN,CHINA', required: true },
      { label: '中转港', value: '请选择中转港' },
      { label: '目的港', code: 'GBFXT', value: 'FELIXSTOWE,UNITED KINGDOM', required: true },
    ],
    secondRow: [
      { label: '目的地', value: 'GBFXT FELIXSTOWE,UNITED KINGDOM' },
      { label: '船名', value: 'COSCOTTTT' },
      { label: '合约号', value: '订舱COSCOTEST' },
      { label: 'ETD', value: '2026-07-05', required: true },
    ],
    thirdRow: [
      { label: '航线', value: 'AEU1  大船船名/航次  OOCL ZEEBRUGGE / 010W' },
      { label: 'ETA', value: '2026-08-08' },
      { label: 'ATD', value: '2026-07-05' },
      { label: 'ATA', value: '2026-08-08' },
    ],
    fourthRow: [
      { label: 'PCD', value: '请选择PCD' },
      { label: '承运条款', value: 'CFS-CFS' },
      { label: '运输方式', value: '海运' },
      { label: '贸易条款', value: 'DAP', required: true },
    ],
    fifthRow: [
      { label: '账单格式', value: 'PTP', required: true },
      { label: '提单格式', value: 'PTP提单', required: true },
      { label: '是否有船期费用', value: '请选择' },
      { label: '付款方式', value: 'FREIGHT PREPAID' },
    ],
    sixthRow: [
      { label: '预计仓库', value: '东莞宝安仓库 / 请选择', required: true },
      { label: '进仓仓库', value: '请选择 / 请选择' },
      { label: '预计进仓时间', value: '2026-06-26' },
      { label: '出库时间', value: '请选择出库时间' },
    ],
    goodsTypes: [
      { label: '普货', active: true },
      { label: '危险货', active: false, risk: true },
      { label: '电池', active: false, risk: true },
      { label: '化工品', active: false, risk: true },
      { label: '液体/粉末', active: false, risk: true },
      { label: '食品', active: false },
      { label: '商检', active: false },
    ],
    bottomRemarks: [
      { label: '客户备注', value: '请输入客户备注' },
      { label: '操作备注', value: '' },
      { label: '业务客服备注', value: '请输入业务客服备注' },
      { label: '境外代理备注', value: '请输入境外代理备注(仅支持输入英文、数字、空格)' },
    ],
    orderTypeTags: [
      { label: '多家拼', active: true },
      { label: '家拼', active: false },
      { label: '三方贸易', active: false },
      { label: '换单', active: false },
    ],
  },
  cargoBlocks: [
    {
      id: 'cargo-1',
      title: '货物信息_1',
      senderName: 'ALIK',
      senderAddress: '111111111111123213123',
      consigneeName: 'qian 测试公司 PPP002',
      consigneeAddress: 'QIAN CESHIGONGSI 00022111 11 123123',
      notifyName: 'SAME AS CONSIGNEE',
      notifyAddress: 'SAME AS CONSIGNEE',
      overseasAgent: 'DCG LOGISTICS UK LTD',
      overseasAgentAddress: 'DCG LOGISTICS UK LTD RENOWN AVE, COVENTRY CV5 6UF',
      vat: '456456546',
      eori: '56456456',
      remark: '备注',
      totalQty: 100,
      totalWeight: 100,
      totalVolume: 10,
      lines: [
        {
          id: 'line-1',
          zhName: '请输入中文品名',
          enName: '请输入英文品名',
          cartons: '请输入唛头',
          hsCode: '请输入HsCode',
          containerNo: 'GPTP6060186',
          qty: 100,
          packageUnit: 'CTNS',
          grossWeight: 100,
          volume: 10,
        },
      ],
    },
  ],
  cabinetRows: [
    {
      id: 'cab-1',
      containerType: 'LCL',
      containerNo: 'GPTP6060186',
      sealNo: 'FPTP26060186',
      soNo: 'SPTP26060186',
      qty: 100,
      packageUnit: 'CTNS',
      grossWeight: 100,
      volume: 10,
      planDeliveryTime: '',
      actualDeliveryTime: '',
      pickupTime: '',
      returnTime: '',
      loadingTime: '',
      releaseStatus: '否',
      weightVolumeRatio: '0.2',
    },
  ],
  customsRows: [
    {
      id: 'customs-1',
      company: '请选择报关公司',
      sender: 'ALIK',
      customsFile: '',
      customsNo: '',
      qty: '',
      packageUnit: '请选择',
      grossWeight: '',
      volume: '',
      customsMethod: '代理报关',
      customsStatus: '未报关',
      releaseStatus: '否',
      uploadTime: '',
      releaseBookingTime: '',
      customsSheet: '点击上传',
      finalConfirmTime: '',
    },
  ],
  warehouseRows: [
    {
      id: 'warehouse-1',
      storageNo: 'UKSZ26060186',
      checkSheet: '点击上传',
      sender: 'ALIK',
      destination: '',
      actualInboundDate: '',
      fbaNo: '',
      pickupLabel: '理货标签',
      qty: 100,
      packageUnit: '包装单位',
      grossWeight: 100,
      volume: 10,
      driverPhone: '请输入司机电话',
      storageImage: '',
      actionLabel: '删除',
    },
  ],
};

const shipmentOrderOverrides: Record<string, Partial<ShipmentOrderDetailRecord>> = {
  PTP25060029: {
    orderNo: 'PTP25060029',
    hblNo: 'PTP25060029',
    mblNo: '123123',
    inStorageNo: 'UKSZ25060029',
    externalOrderNo: 'FCL25060033',
    customerOrderNo: 'FCL25060033',
    customerName: '西门子',
    businessType: '海运拼箱',
    serviceScope: '拖车 / 订舱 / 派送',
    orderDate: '2026-06-20 10:12:00',
    packageMode: 'LCL',
  },
  PTP26010019: {
    orderNo: 'PTP26010019',
    hblNo: 'PTP26010019',
    mblNo: 'SPTP26010019',
    inStorageNo: 'UKSZ26010019',
    externalOrderNo: 'LCL26010017',
    customerOrderNo: 'LCL26010017',
    customerName: '艾力克',
    businessType: 'FBA',
    serviceScope: '全程',
    orderDate: '2026-06-22 08:20:00',
    packageMode: 'LCL GROUP（自拼）',
  },
  PTP26060168: {
    orderNo: 'PTP26060168',
    hblNo: 'PTP26060168',
    mblNo: 'OOLU26060168',
    inStorageNo: 'UKSZ26060168',
    externalOrderNo: 'LCL26060183',
    customerOrderNo: 'LCL26060183',
    customerName: '安迪测试',
    businessType: '海运拼箱',
    serviceScope: '订舱 / 报关',
    orderDate: '2026-06-24 14:33:00',
    packageMode: 'LCL',
  },
  PTP26060186: {
    orderNo: 'PTP26060186',
    hblNo: 'PTP26060186',
    mblNo: 'SPTP26060186',
    inStorageNo: 'UKSZ26060186',
    externalOrderNo: 'UUKDCG25091529',
    customerOrderNo: 'UUKDCG25091529',
    customerName: '艾力克',
    businessType: 'FBA',
    serviceScope: '全程',
    orderDate: '2026-06-26 09:33:19',
    packageMode: 'LCL GROUP（自拼）',
  },
};

export const getShipmentOrderMock = (orderNo?: string): ShipmentOrderDetailRecord => {
  const override = orderNo ? shipmentOrderOverrides[orderNo] : null;
  return {
    ...baseShipmentOrderMock,
    ...(override || {}),
  };
};

export const shipmentOrderMock = getShipmentOrderMock();
