import type { ShipmentOrderDetailRecord } from './types';

const baseDetail: ShipmentOrderDetailRecord = {
  orderNo: 'SEO2026060001',
  orderStatus: 'waitBooking',
  orderStatusLabel: '待订舱',
  statusPill: 'wait',
  customerName: '深圳华贸进出口有限公司',
  businessType: 'FCL',
  vesselVoyage: 'COSCO SHIPPING / 028W',
  pol: 'CNSHA',
  pod: 'USLAX',
  etd: '2026-07-08',
  eta: '2026-07-28',
  operator: '张操作',
  exceptionStatus: '正常',
  profitStatus: '待核算',
  profitStatusKey: 'wait',
  customerContact: '陈经理',
  customerPhone: '13800138001',
  customerEmail: 'chen@huamao.com',
  salesPerson: '刘商务',
  csPerson: '周客服',
  tradeTerm: 'FOB',
  transportTerm: 'CY/CY',
  paymentMethod: '月结30天',
  createdAt: '2026-06-28 10:30',
  orderSource: '业务员录入',
  transitPort: '—',
  carrier: 'COSCO',
  vessel: 'COSCO SHIPPING',
  voyage: '028W',
  closingTime: '2026-07-05 12:00',
  siCutoff: '2026-07-04 12:00',
  bookingNo: '',
  bookingAgent: '深圳订舱代理',
  contractNo: 'CT2026-0881',
  rateNo: 'RATE-SHA-LAX-0726',
  spaceStatus: '待放舱',
  releaseTime: '—',
  vgmCutoff: '2026-07-04 18:00',
  bookingRemark: '客户要求优先配舱，注意截关时间',
  containerSummary: '2×40HQ',
  risks: [
    {
      id: 'r1',
      type: '截关预警',
      level: 'danger',
      message: '截关时间不足 24 小时，报关资料未上传',
      owner: '张操作',
      dueAt: '2026-07-05 12:00',
      status: '待处理',
    },
    {
      id: 'r2',
      type: '文件缺失',
      level: 'warn',
      message: '已放舱但未上传 SO 文件',
      owner: '张操作',
      dueAt: '2026-07-03 18:00',
      status: '待处理',
    },
  ],
  todos: [
    {
      id: 't1',
      type: '订舱确认',
      owner: '张操作',
      dueAt: '2026-06-30 18:00',
      status: '进行中',
    },
    {
      id: 't2',
      type: '上传报关资料',
      owner: '张操作',
      dueAt: '2026-07-04 12:00',
      status: '待处理',
    },
  ],
  nodes: [
    { id: 'n1', name: '订单创建', planTime: '2026-06-28 10:30', actualTime: '2026-06-28 10:30', status: '已完成', statusKey: 'rel', owner: '刘商务', source: '系统', overdue: false },
    { id: 'n2', name: '订舱提交', planTime: '2026-06-29 12:00', actualTime: '2026-06-29 11:20', status: '已完成', statusKey: 'rel', owner: '张操作', source: '订舱', overdue: false },
    { id: 'n3', name: '船司放舱', planTime: '2026-06-30 18:00', actualTime: '—', status: '待完成', statusKey: 'wait', owner: '张操作', source: '订舱', overdue: false },
    { id: 'n4', name: '截关', planTime: '2026-07-05 12:00', actualTime: '—', status: '待完成', statusKey: 'wait', owner: '张操作', source: '系统', overdue: false },
    { id: 'n5', name: '开船', planTime: '2026-07-08 08:00', actualTime: '—', status: '待完成', statusKey: 'wait', owner: '张操作', source: '船期', overdue: false },
  ],
  feeSummary: {
    receivableTotal: 12800,
    payableTotal: 9600,
    grossProfit: 3200,
    grossMargin: 25,
    unconfirmedReceivable: 12800,
    unconfirmedPayable: 9600,
    invoicedAmount: 0,
    paidAmount: 0,
    unpaidReceivable: 12800,
    unpaidPayable: 9600,
  },
  receivableFees: [
    { id: 'rf1', name: '海运费', currency: 'USD', unitPrice: 3200, qty: 2, unit: '柜', amount: 6400, taxRate: 0, taxAmount: 6400, party: '深圳华贸进出口有限公司', status: '待确认', statusKey: 'wait' },
    { id: 'rf2', name: 'THC', currency: 'CNY', unitPrice: 800, qty: 2, unit: '柜', amount: 1600, taxRate: 6, taxAmount: 1696, party: '深圳华贸进出口有限公司', status: '待确认', statusKey: 'wait', invoiceStatus: '未开票', paymentStatus: '未收款' },
  ],
  payableFees: [
    { id: 'pf1', name: '海运费', currency: 'USD', unitPrice: 2800, qty: 2, unit: '柜', amount: 5600, taxRate: 0, taxAmount: 5600, party: 'COSCO 深圳', status: '待确认', statusKey: 'wait', paymentStatus: '未付款' },
    { id: 'pf2', name: '拖车费', currency: 'CNY', unitPrice: 2000, qty: 1, unit: '票', amount: 2000, taxRate: 6, taxAmount: 2120, party: '深圳顺达拖车', status: '待确认', statusKey: 'wait', paymentStatus: '未付款' },
  ],
  files: [
    { id: 'f1', name: '订舱委托书.pdf', category: '订舱文件', uploader: '刘商务', uploadedAt: '2026-06-28 10:35', status: '已上传', statusKey: 'acc', required: true, confirmed: true },
    { id: 'f2', name: 'SO-待上传', category: 'SO 文件', uploader: '—', uploadedAt: '—', status: '缺失', statusKey: 'rej', required: true, confirmed: false },
    { id: 'f3', name: '装箱单.xlsx', category: '装箱单', uploader: '张操作', uploadedAt: '2026-06-29 15:20', status: '待确认', statusKey: 'wait', required: false, confirmed: false },
  ],
  exceptions: [
    {
      id: 'e1',
      no: 'EX2026060001',
      type: '订舱异常',
      level: '中',
      levelKey: 'partial',
      description: '船司舱位紧张，需协调备选船期',
      department: '操作部',
      owner: '张操作',
      occurredAt: '2026-06-29 14:00',
      expectedResolveAt: '2026-06-30 18:00',
      status: '处理中',
      statusKey: 'op',
    },
  ],
  logs: [
    { id: 'l1', time: '2026-06-29 11:20', operator: '张操作', module: '订舱', action: '提交订舱', before: '待订舱', after: '订舱中', source: 'Web' },
    { id: 'l2', time: '2026-06-28 10:30', operator: '刘商务', module: '订单', action: '创建订单', before: '—', after: '草稿', source: 'Web' },
  ],
};

const overrides: Record<string, Partial<ShipmentOrderDetailRecord>> = {
  SEO2026060003: {
    orderNo: 'SEO2026060003',
    orderStatus: 'customs',
    orderStatusLabel: '报关中',
    statusPill: 'op',
    customerName: '广州宏达电子科技',
    exceptionStatus: '异常',
    profitStatus: '已核算',
    profitStatusKey: 'rel',
  },
  SEO2026060004: {
    orderNo: 'SEO2026060004',
    orderStatus: 'sailed',
    orderStatusLabel: '已开船',
    statusPill: 'rel',
    customerName: '上海瑞联物流',
    profitStatus: '已确认',
    profitStatusKey: 'acc',
  },
};

export const getShipmentOrderMock = (orderNo?: string): ShipmentOrderDetailRecord => {
  const override = orderNo ? overrides[orderNo] : undefined;
  return {
    ...baseDetail,
    ...(override ?? {}),
    orderNo: orderNo ?? baseDetail.orderNo,
  };
};
