import type { ShipmentWorkbenchRow } from './types';

const baseRows: ShipmentWorkbenchRow[] = [
  {
    id: '1',
    orderNo: 'SEO2026060001',
    customerName: '深圳华贸进出口有限公司',
    businessType: 'FCL',
    orderStatus: 'waitBooking',
    orderStatusLabel: '待订舱',
    statusPill: 'wait',
    carrier: 'COSCO',
    vesselVoyage: 'COSCO SHIPPING / 028W',
    pol: 'CNSHA',
    pod: 'USLAX',
    etd: '2026-07-08',
    eta: '2026-07-28',
    closingTime: '2026-07-05 12:00',
    blNo: '',
    bookingNo: '',
    containerSummary: '2×40HQ',
    operator: '张操作',
    fileStatus: 'missing',
    fileStatusLabel: '缺失',
    feeStatus: 'none',
    feeStatusLabel: '未生成',
    exceptionStatus: 'normal',
    exceptionStatusLabel: '正常',
    updatedAt: '2026-06-30 09:12',
    riskFlags: ['file'],
    quickStatus: ['all', 'waitBooking', 'fileMissing'],
    isOverdue: false,
    todayNew: true,
  },
  {
    id: '2',
    orderNo: 'SEO2026060002',
    customerName: '宁波远洋贸易集团',
    businessType: 'FCL',
    orderStatus: 'released',
    orderStatusLabel: '已放舱',
    statusPill: 'rel',
    carrier: 'EVERGREEN',
    vesselVoyage: 'EVER GOLDEN / 115E',
    pol: 'CNNGB',
    pod: 'DEHAM',
    etd: '2026-07-12',
    eta: '2026-08-02',
    closingTime: '2026-07-09 18:00',
    blNo: 'EGLV123456789',
    bookingNo: 'BK2026068801',
    containerSummary: '1×40HQ + 1×20GP',
    operator: '李操作',
    fileStatus: 'pending',
    fileStatusLabel: '待确认',
    feeStatus: 'pending',
    feeStatusLabel: '待确认',
    exceptionStatus: 'normal',
    exceptionStatusLabel: '正常',
    updatedAt: '2026-06-29 16:45',
    riskFlags: ['fee'],
    quickStatus: ['all', 'waitRelease', 'waitTruck', 'feeUnconfirmed'],
    isOverdue: false,
    todayNew: false,
  },
  {
    id: '3',
    orderNo: 'SEO2026060003',
    customerName: '广州宏达电子科技',
    businessType: 'LCL',
    orderStatus: 'customs',
    orderStatusLabel: '报关中',
    statusPill: 'op',
    carrier: 'MSC',
    vesselVoyage: 'MSC OSCAR / 044W',
    pol: 'CNSZX',
    pod: 'NLRTM',
    etd: '2026-07-03',
    eta: '2026-07-25',
    closingTime: '2026-06-30 17:00',
    blNo: 'MSCU998877665',
    bookingNo: 'BK2026067702',
    containerSummary: '3×40HQ',
    operator: '王操作',
    fileStatus: 'complete',
    fileStatusLabel: '完整',
    feeStatus: 'confirmed',
    feeStatusLabel: '已确认',
    exceptionStatus: 'open',
    exceptionStatusLabel: '异常',
    updatedAt: '2026-06-30 08:30',
    riskFlags: ['exception', 'overdue'],
    quickStatus: ['all', 'waitCustoms', 'exception'],
    isOverdue: true,
    todayNew: true,
  },
  {
    id: '4',
    orderNo: 'SEO2026060004',
    customerName: '上海瑞联物流',
    businessType: 'FCL',
    orderStatus: 'sailed',
    orderStatusLabel: '已开船',
    statusPill: 'rel',
    carrier: 'CMA CGM',
    vesselVoyage: 'CMA CGM MARCO POLO / 88W',
    pol: 'CNSHA',
    pod: 'FRLEH',
    etd: '2026-06-28',
    eta: '2026-07-18',
    closingTime: '2026-06-25 12:00',
    blNo: 'CMAU556677889',
    bookingNo: 'BK2026066603',
    containerSummary: '2×40GP',
    operator: '赵操作',
    fileStatus: 'pending',
    fileStatusLabel: '待确认',
    feeStatus: 'confirmed',
    feeStatusLabel: '已确认',
    exceptionStatus: 'normal',
    exceptionStatusLabel: '正常',
    updatedAt: '2026-06-28 14:20',
    riskFlags: ['bl'],
    quickStatus: ['all', 'sailed', 'waitSi', 'waitBlConfirm'],
    isOverdue: false,
    todayNew: false,
  },
  {
    id: '5',
    orderNo: 'SEO2026060005',
    customerName: '青岛海盛实业',
    businessType: 'FCL',
    orderStatus: 'trucking',
    orderStatusLabel: '拖车中',
    statusPill: 'op',
    carrier: 'OOCL',
    vesselVoyage: 'OOCL HONG KONG / 201E',
    pol: 'CNTAO',
    pod: 'SGSIN',
    etd: '2026-07-15',
    eta: '2026-07-28',
    closingTime: '2026-07-12 10:00',
    blNo: '',
    bookingNo: 'BK2026065504',
    containerSummary: '1×40HQ',
    operator: '张操作',
    fileStatus: 'complete',
    fileStatusLabel: '完整',
    feeStatus: 'pending',
    feeStatusLabel: '待确认',
    exceptionStatus: 'normal',
    exceptionStatusLabel: '正常',
    updatedAt: '2026-06-30 10:05',
    riskFlags: [],
    quickStatus: ['all', 'waitTruck', 'waitLoading'],
    isOverdue: false,
    todayNew: true,
  },
  {
    id: '6',
    orderNo: 'SEO2026060006',
    customerName: '厦门建发供应链',
    businessType: 'FCL',
    orderStatus: 'waitCustoms',
    orderStatusLabel: '待报关',
    statusPill: 'wait',
    carrier: 'YANG MING',
    vesselVoyage: 'YANG MING / 332W',
    pol: 'CNXMN',
    pod: 'JPYOK',
    etd: '2026-07-06',
    eta: '2026-07-16',
    closingTime: '2026-07-01 08:00',
    blNo: 'YMLU445566778',
    bookingNo: 'BK2026064405',
    containerSummary: '2×20GP',
    operator: '李操作',
    fileStatus: 'missing',
    fileStatusLabel: '缺失',
    feeStatus: 'none',
    feeStatusLabel: '未生成',
    exceptionStatus: 'normal',
    exceptionStatusLabel: '正常',
    updatedAt: '2026-06-29 11:18',
    riskFlags: ['file', 'overdue'],
    quickStatus: ['all', 'waitCustoms', 'fileMissing'],
    isOverdue: true,
    todayNew: false,
  },
  {
    id: '7',
    orderNo: 'SEO2026050028',
    customerName: '天津港联国际',
    businessType: 'FCL',
    orderStatus: 'completed',
    orderStatusLabel: '已完成',
    statusPill: 'rel',
    carrier: 'HMM',
    vesselVoyage: 'HMM ALGECIRAS / 009E',
    pol: 'CNTXG',
    pod: 'KRPUS',
    etd: '2026-05-20',
    eta: '2026-06-02',
    closingTime: '2026-05-17 16:00',
    blNo: 'HMMU334455667',
    bookingNo: 'BK2026053301',
    containerSummary: '1×40HQ',
    operator: '王操作',
    fileStatus: 'complete',
    fileStatusLabel: '完整',
    feeStatus: 'confirmed',
    feeStatusLabel: '已确认',
    exceptionStatus: 'resolved',
    exceptionStatusLabel: '已处理',
    updatedAt: '2026-06-10 09:00',
    riskFlags: [],
    quickStatus: ['all'],
    isOverdue: false,
    todayNew: false,
  },
  {
    id: '8',
    orderNo: 'SEO2026060008',
    customerName: '东莞精密制造',
    businessType: 'FCL',
    orderStatus: 'booking',
    orderStatusLabel: '订舱中',
    statusPill: 'op',
    carrier: 'ONE',
    vesselVoyage: 'ONE INNOVATION / 077W',
    pol: 'CNSZX',
    pod: 'USNYC',
    etd: '2026-07-20',
    eta: '2026-08-10',
    closingTime: '2026-07-17 14:00',
    blNo: '',
    bookingNo: 'BK2026062208',
    containerSummary: '4×40HQ',
    operator: '赵操作',
    fileStatus: 'pending',
    fileStatusLabel: '待确认',
    feeStatus: 'pending',
    feeStatusLabel: '待确认',
    exceptionStatus: 'open',
    exceptionStatusLabel: '异常',
    updatedAt: '2026-06-30 07:55',
    riskFlags: ['exception', 'fee'],
    quickStatus: ['all', 'waitBooking', 'feeUnconfirmed', 'exception'],
    isOverdue: false,
    todayNew: true,
  },
];

const operators = ['张操作', '李操作', '王操作', '赵操作'] as const;

export const shipmentWorkbenchRows: ShipmentWorkbenchRow[] = [
  ...baseRows,
  ...baseRows.map((row, index) => {
    const seq = index + 9;
    return {
      ...row,
      id: String(seq),
      orderNo: `SEO202606${String(1000 + seq).slice(1)}`,
      operator: operators[index % operators.length],
      todayNew: index % 4 === 0,
      isOverdue: index % 5 === 2,
      updatedAt: `2026-06-${String(28 - (index % 5)).padStart(2, '0')} ${10 + (index % 8)}:${15 + index}`,
    };
  }),
  ...baseRows.slice(0, 8).map((row, index) => {
    const seq = index + 17;
    return {
      ...row,
      id: String(seq),
      orderNo: `SEO202605${String(2000 + seq).slice(1)}`,
      operator: operators[(index + 2) % operators.length],
      orderStatus: index % 2 === 0 ? 'released' as const : 'waitBooking' as const,
      orderStatusLabel: index % 2 === 0 ? '已放舱' : '待订舱',
      statusPill: index % 2 === 0 ? 'rel' : 'wait',
      todayNew: false,
      isOverdue: false,
    };
  }),
];
