import type { ShipmentWorkbenchRow } from './types';

export const shipmentWorkbenchRows: ShipmentWorkbenchRow[] = [
  {
    id: '1',
    orderNo: 'PTP25060029',
    orderStatus: '归档',
    orderStatusKey: 'draft',
    suborderStatus: '查看',
    suborderNo: '',
    cargoType: '普货',
    financePod: '-',
    feeLink: '查看',
    qty: 0,
    grossWeight: 0,
    volume: 0,
    containerType: '中转拼箱派送',
    businessNo: 'FCL25060033',
    externalOrderNo: '',
    pushBeforeVessel: false,
    customer: '西门子',
    contractNo: '',
    destinationInfo: '查看',
    cabinetNo: '1X20\'GP',
    departurePort: 'YANTIAN',
    hblNo: '1111',
    soNo: '',
    mblNo: '123123',
    documentDownload: true,
    quickTag: '全部',
    cargoScope: 'fcl',
    salesperson: '张三',
    operator: '王五',
    businessType: '海运拼箱',
    packageMode: 'LCL',
  },
  {
    id: '2',
    orderNo: 'PTP26010019',
    orderStatus: '已装单',
    orderStatusKey: 'rel',
    suborderStatus: '查看',
    suborderNo: '',
    cargoType: '普货',
    financePod: '-',
    feeLink: '查看',
    qty: 100,
    grossWeight: 100,
    volume: 10,
    containerType: '亚马逊柜',
    businessNo: 'LCL26010017',
    externalOrderNo: '',
    pushBeforeVessel: false,
    customer: '艾力克',
    contractNo: '订舱COSCOTEST',
    destinationInfo: '查看',
    cabinetNo: 'LCL',
    departurePort: '港口英文名',
    hblNo: 'PTP26010019',
    soNo: 'SPTP26010019',
    mblNo: '',
    documentDownload: true,
    quickTag: '整柜',
    cargoScope: 'fcl',
    salesperson: '李四',
    operator: '赵六',
    businessType: 'FBA',
    packageMode: 'LCL GROUP（自拼）',
  },
  {
    id: '3',
    orderNo: 'PTP26060168',
    orderStatus: '已装单',
    orderStatusKey: 'rel',
    suborderStatus: '查看',
    suborderNo: '',
    cargoType: '普货',
    financePod: '-',
    feeLink: '查看',
    qty: 0,
    grossWeight: 0,
    volume: 0,
    containerType: 'LCL',
    businessNo: 'LCL26060183',
    externalOrderNo: '',
    pushBeforeVessel: false,
    customer: '安迪测试',
    contractNo: '',
    destinationInfo: '查看',
    cabinetNo: 'LCL',
    departurePort: 'NINGBO',
    hblNo: 'PTP26060168',
    soNo: '',
    mblNo: '',
    documentDownload: true,
    quickTag: '散货',
    cargoScope: 'lcl',
    salesperson: '王五',
    operator: '王五',
    businessType: '海运拼箱',
    packageMode: 'LCL',
  },
  {
    id: '4',
    orderNo: 'PTP26060186',
    orderStatus: '放舱',
    orderStatusKey: 'op',
    suborderStatus: '查看',
    suborderNo: '',
    cargoType: '普货',
    financePod: '-',
    feeLink: '查看',
    qty: 100,
    grossWeight: 100,
    volume: 10,
    containerType: '亚马逊柜',
    businessNo: 'LCL26060200',
    externalOrderNo: 'UUKDCG25091529',
    pushBeforeVessel: true,
    customer: '艾力克',
    contractNo: '订舱COSCOTEST',
    destinationInfo: '查看',
    cabinetNo: 'LCL',
    departurePort: 'YANTIAN',
    hblNo: 'PTP26060186',
    soNo: 'SPTP26060186',
    mblNo: 'SPTP26060186',
    documentDownload: true,
    quickTag: '全部',
    cargoScope: 'lcl',
    salesperson: '李四',
    operator: '张三',
    businessType: 'FBA',
    packageMode: 'LCL GROUP（自拼）',
  },
];
