import { definePesdpPageSpec } from '@/design-system/pesdpPageSpec';

export const EXPORT_ORDER_WORKBENCH_SPEC = definePesdpPageSpec({
  id: 'shipment-export-order-workbench',
  target: 'sellable-saas-grade',
  presentationTarget: 'daily-ops',
  archetype: 'list-workbench',
  input: { path: 'artifact', artifacts: ['user-provided anchored operations-grid column-settings screenshot'], unresolvedBusinessDecisions: ['production order API, permission, workflow-transition sources, and shared column-template creation'], recommendations: ['preserve local acceptance behavior until production contracts are supplied; implement real local column visibility without inventing saved-template creation'] },
  list: {
    frame: 'standard-list-v1',
    profile: 'operations-workbench',
    commandSurface: 'workbench',
    tableTop: 'workbench-toolbar',
    selection: 'batch',
    workScope: 'required',
    statusQueues: 'required',
    views: {
      pageMode: 'none',
      pageModeCount: 0,
      workflowState: 'line-tabs',
      workflowStateCount: 12,
      workflowStatePlacement: 'workflow-row',
      workflowStateOverflow: 'local-scroll',
    },
  },
  business: {
    object: 'sea-export-order',
    primaryUser: 'freight-operator',
    userJob: 'locate-prioritize-and-progress-orders',
    primaryIdentity: ['orderNo'],
    keyState: ['status', 'nextAction', 'exceptionState'],
    mainWorkingData: ['owner', 'customer', 'route', 'etd', 'documentState', 'feeState'],
    supportingData: ['updatedAt'],
  },
  pesdp: {
    professional: {
      decisions: ['Use sea-export order vocabulary, ownership scope, operational queues, and the next freight action; treat processing queue as a high-frequency workflow-state query dimension rather than page navigation or a mutation; separate locate, workflow, queue, and table-utility jobs into readable zones instead of one continuous control strip; use a standard grouped admin navigation shell without inventing unavailable modules or routes; every row-changing action must expose a complete result.'],
      acceptance: [
        'Rendered columns must expose order identity, owner, route, status, and next action without generic task wording.',
        'The first viewport makes query, new/batch workflow, ownership scope, processing queue, and table utilities distinguishable without decorative cards or duplicate labels.',
        'Ownership scope and processing queue share one mutation-free state row below query; create, export, and batch commands live in the table toolbar below that row and immediately above the rows they affect.',
        'Self-explanatory scope and queue options do not repeat visible group captions; their Radio/Tabs controls retain business-specific accessible names.',
        'No context sentence may repeat work-scope or queue labels that are already selected in controls.',
        'The current route remains visible in a compact, grouped navigation menu without workspace-card chrome competing with the workbench.',
      ],
    },
    efficient: {
      decisions: ['Keep daily query fields, ownership scope, status queues, assignment, notification, and batch entry directly reachable; do not render disabled placeholder actions without a feature contract.'],
      acceptance: [
        'At 1366x768 the command path must remain one compact surface, query actions must sit with the query cluster, and the table must own at least 70% of usable height.',
        'Batch assignment and notification must update the selected orders instead of only showing a toast.',
        'Query and every mutation must expose a stable pending state and preserve user context on failure.',
        'Advanced boolean conditions use direct three-state controls and every business group can clear only its own draft values.',
      ],
    },
    structured: {
      decisions: ['Use the shared standard-list frame to keep query, workflow state, table toolbar, feedback, and data in one stable order; query surface owns a bounded query cluster followed by a mutation-free ownership/workflow-state row; data surface owns table business commands, selection context, utilities, pagination, and rows.'],
      acceptance: [
        'Totals must appear in pagination and queue counts only; table context must not repeat the total, active scope, active queue, or risk count.',
        'Advanced query, status change, batch assignment, and column settings each have one explicit overlay owner.',
      ],
    },
    dense: {
      decisions: ['Keep the identifier locate field as one connected selector plus shared batch-value query using the semantic batch allocation: one value remains directly editable, multi-paste normalizes and de-duplicates values immediately, and review/clear stay directly reachable. Treat every permitted query field as belonging to exactly one user-configurable location: the aligned page surface or the D1 filter drawer. Use one logical-unit grid with six minimum units, reserve two units for the localized query command group, and reject any placement that would exceed two rows. Keep the identifier field required and first; preserve values when fields move; persist only versioned stable field ids and never run a query when saving placement. Edit drawer fields in freight business groups using two readable columns and one native scroll owner.'],
      acceptance: [
        'At 1366, 1024 split, and wide viewports, the query row does not create a separate action band, adjacent query-action boxes keep the same 8px gap, and the table remains the dominant work surface.',
        'At compact table-toolbar width, create and batch remain reachable, optional export text collapses, pagination hides jumper then page-size, and total plus page navigation remain visible on one line.',
        'Vertical query and overlay forms use the shared 4px label-to-control rhythm through the Arco public label-column style.',
        'The advanced-filter grid uses the shared 12px column and 8px row gutter with zero form-item margin, so no page-local spacing layer enlarges the dense form rhythm.',
        'At 1024, the identifier query keeps the largest field allocation, reset and advanced-filter keep visible labels, the configured page fields and action group remain aligned within two rows, and the 12 processing queues move to a deterministic second workflow line where they scroll only inside their own lane.',
        'The document-number query accepts one direct value or up to 100 pasted values separated by whitespace or common punctuation, preserves first-seen order and case, removes duplicates, exposes the normalized values plus count, and matches any entered value within the selected identifier type.',
        'The advanced filter opens from the right at the shared D1 width, renders two field columns, and keeps the native Drawer body as its only vertical scroll owner.',
        'Query-field settings exposes ordered page and drawer lists with mouse drag, keyboard reordering, explicit move commands, restore defaults, capacity validation, and failure-preserving persistence; saving placement does not change query values, page, selection, or result data.',
        'Drawer content and footer remain horizontally contained at 1024, 1366, and wide desktop viewports.',
      ],
    },
    premium: {
      decisions: ['Keep GI and VXE native component styling; derive product quality from field allocation, context-preserving overlays, freight grouping, live result confidence, visible draft state, complete states, and a restrained row-action hierarchy: expose one legal next row action, move supporting work into More, and keep danger in the final confirmed menu group.', 'Use one shared Arco-anchored column-preference panel with one ungrouped scroll-owned checklist, drag handles for movable business-column order, required-column protection, show-all, restore-default, save, and immediate VXE visibility/order application; saved column-template creation remains outside scope until its persistence contract exists.', 'Configure query placement through a proportional page-query preview above a searchable full-width drawer catalog; use vertical move icons, stable hover/drag feedback, and no alternate overlay skin.'],
      acceptance: [
        'The advanced drawer exposes route/document, execution/ownership, schedule, and risk groups with local active counts, local reset, and a live matching-order count without a page-local component skin.',
        'The default advanced-filter interaction preserves the list beside a stable right-side drawer and never changes to a top overlay.',
        'Computed theme tokens, normal/error/empty/permission states, long text, query-placement search/capacity/drag feedback, and column settings must be inspected on the real route.',
        'The route must not depend on global selectors or theme-variable bridges that rewrite Arco or VXE internals.',
        'Each row exposes one emphasized legal next action followed by neutral More; self-assignment remains reachable in More when status transition owns the direct slot, and irreversible actions are danger-styled only inside the final menu group.',
        'The order-status column must show the longest supported localized status pill in full; the operation column must contain its longest legal localized action set without cell-level horizontal scrolling, and focusing More must not shift the row-action origin.',
        'The column-settings utility opens beside its gear trigger, keeps one ungrouped checklist locally scrollable, protects required columns and the minimum selection, supports mouse drag order with a visible handle, restores defaults, persists a valid visible-and-ordered selection, and applies real VXE visibility and order without a page-level modal.',
        'Refresh and column settings remain one icon group before a divider; the rightmost pagination uses Arco mini density and no page-local typography override.',
      ],
    },
  },
  surfaces: [
    { id: 'app-navigation', role: 'supporting', owns: ['module-navigation', 'route-identity'], implementation: 'arco' },
    { id: 'command', role: 'command', owns: ['query', 'ownership-scope', 'status-queues'], primaryAction: 'export-order-query', implementation: 'shared-pattern', whyArcoNotEnough: 'The routed list pages need one reusable owner for query, workflow, table, and overflow height relationships while Arco continues to own each surface.' },
    { id: 'advanced-query', role: 'supporting', owns: ['right-drawer-grid', 'advanced-query-draft', 'freight-business-grouping', 'group-active-counts', 'group-reset', 'live-result-preview', 'draft-dirty-state', 'cancel-apply-state'], primaryAction: 'export-order-query', implementation: 'arco' },
    { id: 'query-preferences', role: 'supporting', owns: ['page-and-drawer-placement', 'query-field-order', 'single-row-capacity', 'preference-persistence'], primaryAction: 'export-order-query-preferences', implementation: 'shared-pattern', whyArcoNotEnough: 'Arco owns the drawer and controls; the shared pattern owns cross-list ordering, capacity validation, normalization, and preference persistence.' },
    { id: 'orders', role: 'data', owns: ['create', 'export', 'batch-actions', 'table-data', 'selection', 'batch-result', 'column-settings', 'pagination', 'total-count', 'table-feedback'], primaryAction: 'export-order-create', implementation: 'shared-pattern', whyArcoNotEnough: 'Freight list grids require the shared VXE workbench wrapper and public fixed-column, overflow, loading, and preference configuration.' },
  ],
  query: {
    totalFields: 18,
    strategy: 'page-and-drawer',
    layout: 'semantic-grid-v1',
    visibleFields: ['keyword', 'businessType', 'customerName'],
    visibleFieldLayout: [
      { field: 'keyword', width: 'batch' },
      { field: 'businessType', width: 'compact' },
      { field: 'customerName', width: 'standard' },
    ],
    layoutContract: { maxRows: 2, minimumUnits: 6, actionUnits: 2, capacityUnits: 10 },
    advancedFields: [
      'operator',
      'pol',
      'pod',
      'carrier',
      'vesselVoyage',
      'blNo',
      'bookingNo',
      'orderStatus',
      'hasException',
      'etdRange',
      'closingRange',
      'updatedRange',
      'fileStatus',
      'feeStatus',
      'isOverdue',
    ],
    personalization: {
      mode: 'page-and-drawer',
      pageRows: 2,
      minimumUnits: 6,
      actionUnits: 2,
      capacityUnits: 10,
      requiredPageFields: ['keyword'],
      ordering: 'page-global-drawer-grouped',
      persistence: 'local-workspace',
    },
  },
  table: {
    kind: 'workbench',
    rowBanding: 'striped',
    identityColumns: ['sequence', 'orderNo', 'status'],
    decisionColumns: ['nextAction', 'operator', 'customerName', 'route', 'documentState', 'feeState', 'exceptionState'],
    supportingColumns: ['updatedAt'],
    fixed: ['checkbox', 'sequence', 'orderNo', 'operations'],
    densityReason: 'The global mini density keeps the repeated operational list compact and consistent across workbenches.',
    rowActions: { presentation: 'icon-tooltip', maxVisibleEntries: 3, directEntriesWithOverflow: 2, dangerPlacement: 'overflow-only' },
  },
  detail: { mode: 'none', focus: [], milestones: [] },
  actions: [
    { id: 'export-order-query', scope: 'query', frequency: 'daily', risk: 'low', presentation: 'primary', contract: 'export-order-query', successOwner: 'orders', failureOwner: 'orders' },
    { id: 'export-order-query-preferences', scope: 'query', frequency: 'regular', risk: 'low', presentation: 'secondary', contract: 'export-order-query-preferences', successOwner: 'query-preferences', failureOwner: 'query-preferences' },
    { id: 'export-order-create', scope: 'command', frequency: 'daily', risk: 'low', presentation: 'primary', contract: 'export-order-create', successOwner: 'orders', failureOwner: 'orders' },
    { id: 'export-order-batch-action', scope: 'selection', frequency: 'regular', risk: 'medium', presentation: 'dropdown', contract: 'export-order-batch-action', successOwner: 'orders', failureOwner: 'orders' },
    { id: 'export-order-status-transition', scope: 'row', frequency: 'regular', risk: 'medium', presentation: 'row-action', contract: 'export-order-status-transition', successOwner: 'orders', failureOwner: 'orders' },
    { id: 'export-order-assign-self', scope: 'row', frequency: 'regular', risk: 'low', presentation: 'dropdown', contract: 'export-order-assign-self', successOwner: 'orders', failureOwner: 'orders' },
    { id: 'export-order-generate-fee', scope: 'row', frequency: 'regular', risk: 'low', presentation: 'dropdown', contract: 'export-order-generate-fee', successOwner: 'orders', failureOwner: 'orders' },
    { id: 'export-order-notify', scope: 'row', frequency: 'regular', risk: 'low', presentation: 'dropdown', contract: 'export-order-notify', successOwner: 'orders', failureOwner: 'orders' },
    { id: 'export-order-void', scope: 'row', frequency: 'rare', risk: 'high', presentation: 'dropdown', contract: 'export-order-void', successOwner: 'orders', failureOwner: 'orders' },
    { id: 'export-order-column-preferences', scope: 'data-utilities', frequency: 'regular', risk: 'low', presentation: 'text', contract: 'export-order-column-preferences', successOwner: 'orders', failureOwner: 'orders' },
  ],
  states: ['loading', 'slow', 'empty', 'no-permission', 'network-error', 'long-text', 'extreme-value', 'partial-failure', 'success'],
  responsive: { release: ['1366x768', '1280x720'], split: '1024x768', wide: '1920x1080' },
  accessibility: {
    keyboard: ['Reach and operate query, queues, table utilities, row actions, pagination, and every opened overlay in a logical order.'],
    naming: ['Every icon-only command and state-changing control exposes a business-specific accessible name.'],
    zoom: '200%',
  },
  authorities: ['list-page.md', 'filter-layout.md', 'table.md', 'actions.md', 'detail-form.md', 'modal.md', 'overlay-dimensions.md', 'feedback.md', 'responsive.md'],
  verification: ['node scripts/check-spec.js', 'npm run build', 'real-route viewport and state matrix'],
});
