import { definePesdpPageSpec } from '../../../design-system/pesdpPageSpec';

export const EXPORT_ORDER_WORKBENCH_SPEC = definePesdpPageSpec({
  id: 'shipment-export-order-workbench',
  target: 'sellable-saas-grade',
  archetype: 'list-workbench',
  list: {
    frame: 'standard-list-v1',
    profile: 'operations-workbench',
    commandSurface: 'workbench',
    tableTop: 'workbench-toolbar',
    selection: 'batch',
    workScope: 'required',
    statusQueues: 'required',
    views: {
      pageMode: 'none',
      pageModeCount: 0,
      workflowState: 'line-tabs',
      workflowStateCount: 12,
      workflowStatePlacement: 'workflow-row',
      workflowStateOverflow: 'local-scroll',
    },
  },
  business: {
    object: 'sea-export-order',
    primaryUser: 'freight-operator',
    userJob: 'locate-prioritize-and-progress-orders',
    primaryIdentity: ['orderNo'],
    keyState: ['status', 'nextAction', 'exceptionState'],
    mainWorkingData: ['owner', 'customer', 'route', 'etd', 'documentState', 'feeState'],
    supportingData: ['updatedAt'],
  },
  pesdp: {
    professional: {
      decisions: ['Use sea-export order vocabulary, ownership scope, operational queues, and the next freight action; treat processing queue as a high-frequency workflow-state query dimension rather than page navigation or a mutation; separate locate, workflow, queue, and table-utility jobs into readable zones instead of one continuous control strip; use a standard grouped admin navigation shell without inventing unavailable modules or routes; every row-changing action must expose a complete result.'],
      acceptance: [
        'Rendered columns must expose order identity, owner, route, status, and next action without generic task wording.',
        'The first viewport makes query, new/batch workflow, ownership scope, processing queue, and table utilities distinguishable without decorative cards or duplicate labels.',
        'Ownership scope and processing queue share one mutation-free state row below query; create, export, and batch commands live in the table toolbar below that row and immediately above the rows they affect.',
        'Self-explanatory scope and queue options do not repeat visible group captions; their Radio/Tabs controls retain business-specific accessible names.',
        'No context sentence may repeat work-scope or queue labels that are already selected in controls.',
        'The current route remains visible in a compact, grouped navigation menu without workspace-card chrome competing with the workbench.',
      ],
    },
    efficient: {
      decisions: ['Keep daily query fields, ownership scope, status queues, assignment, notification, and batch entry directly reachable; do not render disabled placeholder actions without a feature contract.'],
      acceptance: [
        'At 1366x768 the command path must remain one compact surface, query actions must sit with the query cluster, and the table must own at least 70% of usable height.',
        'Batch assignment and notification must update the selected orders instead of only showing a toast.',
        'Query and every mutation must expose a stable pending state and preserve user context on failure.',
        'Advanced boolean conditions use direct three-state controls and every business group can clear only its own draft values.',
      ],
    },
    structured: {
      decisions: ['Query surface owns a bounded query cluster followed by a mutation-free ownership/workflow-state row; data surface owns table business commands, selection context, utilities, pagination, and rows.'],
      acceptance: [
        'Totals must appear in pagination and queue counts only; table context must not repeat the total, active scope, active queue, or risk count.',
        'Advanced query, status change, batch assignment, and column settings each have one explicit overlay owner.',
      ],
    },
    dense: {
      decisions: ['Keep business type, identifier, customer, and responsible operator as four daily locate fields on one stable row; edit fourteen secondary route, schedule, status/risk, document, and settlement conditions in a right-side D1 drawer using two readable columns and one native scroll owner.'],
      acceptance: [
        'At 1366, 1024 split, and wide viewports, the query row does not create a separate action band and the table remains the dominant work surface.',
        'At compact table-toolbar width, create and batch remain reachable, optional export text collapses, pagination hides jumper then page-size, and total plus page navigation remain visible on one line.',
        'Vertical query and overlay forms use the shared 4px label-to-control rhythm through the Arco public label-column style.',
        'At 1024, the identifier query keeps the largest field allocation, reset and advanced-filter keep visible labels, and the 12 processing queues move to a deterministic second workflow line where they scroll only inside their own lane.',
        'The advanced filter opens from the right at the shared D1 width, renders two field columns, and keeps the native Drawer body as its only vertical scroll owner.',
        'Drawer content and footer remain horizontally contained at 1024, 1366, and wide desktop viewports.',
      ],
    },
    premium: {
      decisions: ['Keep GI and VXE native component styling; derive product quality from field allocation, context-preserving overlays, freight grouping, live result confidence, visible draft state, complete states, and a restrained row-action hierarchy: current next action uses the primary emphasis, supporting and overflow actions stay neutral, and danger appears only in the final confirmed menu group.'],
      acceptance: [
        'The advanced drawer exposes route/document, execution/ownership, schedule, and risk groups with local active counts, local reset, and a live matching-order count without a page-local component skin.',
        'The default advanced-filter interaction preserves the list beside a stable right-side drawer and never changes to a top overlay.',
        'Computed theme tokens, normal/error/empty/permission states, long text, and column settings must be inspected on the real route.',
        'The route must not depend on global selectors or theme-variable bridges that rewrite Arco or VXE internals.',
        'Row actions must not render as an all-blue command strip: status transition is the emphasized next action, self-assignment and More are neutral at rest, and irreversible actions are danger-styled only inside the final menu group.',
        'The operation column must contain its longest legal localized action set without cell-level horizontal scrolling; focusing More must not shift the row-action origin.',
        'Refresh and column settings remain one icon group before a divider; the rightmost pagination uses Arco mini density and no page-local typography override.',
      ],
    },
  },
  surfaces: [
    { id: 'app-navigation', role: 'supporting', owns: ['module-navigation', 'route-identity'], implementation: 'arco' },
    { id: 'command', role: 'command', owns: ['query', 'ownership-scope', 'status-queues'], primaryAction: 'export-order-query', implementation: 'arco' },
    { id: 'advanced-query', role: 'supporting', owns: ['right-drawer-grid', 'advanced-query-draft', 'freight-business-grouping', 'group-active-counts', 'group-reset', 'live-result-preview', 'draft-dirty-state', 'cancel-apply-state'], primaryAction: 'export-order-query', implementation: 'arco' },
    { id: 'orders', role: 'data', owns: ['create', 'export', 'batch-actions', 'table-data', 'selection', 'batch-result', 'column-settings', 'pagination', 'total-count', 'table-feedback'], primaryAction: 'export-order-create', implementation: 'shared-pattern', whyArcoNotEnough: 'Freight list grids require the shared VXE workbench wrapper and public fixed-column, overflow, loading, and preference configuration.' },
  ],
  query: {
    totalFields: 18,
    strategy: 's3-drawer',
    layout: 'semantic-grid-v1',
    visibleFields: ['keyword', 'businessType', 'customerName', 'operator'],
    visibleFieldLayout: [
      { field: 'keyword', width: 'composite' },
      { field: 'businessType', width: 'compact' },
      { field: 'customerName', width: 'standard' },
      { field: 'operator', width: 'compact' },
    ],
    advancedFields: [
      'pol',
      'pod',
      'carrier',
      'vesselVoyage',
      'blNo',
      'bookingNo',
      'orderStatus',
      'hasException',
      'etdRange',
      'closingRange',
      'updatedRange',
      'fileStatus',
      'feeStatus',
      'isOverdue',
    ],
  },
  table: {
    kind: 'workbench',
    identityColumns: ['sequence', 'orderNo', 'status'],
    decisionColumns: ['nextAction', 'operator', 'customerName', 'route', 'documentState', 'feeState', 'exceptionState'],
    supportingColumns: ['updatedAt'],
    fixed: ['checkbox', 'sequence', 'orderNo', 'operations'],
    densityReason: 'The global mini density keeps the repeated operational list compact and consistent across workbenches.',
  },
  detail: { mode: 'none', focus: [], milestones: [] },
  actions: [
    { id: 'export-order-query', scope: 'query', frequency: 'daily', risk: 'low', presentation: 'primary', contract: 'export-order-query', successOwner: 'orders', failureOwner: 'orders' },
    { id: 'export-order-create', scope: 'command', frequency: 'daily', risk: 'low', presentation: 'primary', contract: 'export-order-create', successOwner: 'orders', failureOwner: 'orders' },
    { id: 'export-order-batch-action', scope: 'selection', frequency: 'regular', risk: 'medium', presentation: 'dropdown', contract: 'export-order-batch-action', successOwner: 'orders', failureOwner: 'orders' },
    { id: 'export-order-status-transition', scope: 'row', frequency: 'regular', risk: 'medium', presentation: 'dropdown', contract: 'export-order-status-transition', successOwner: 'orders', failureOwner: 'orders' },
    { id: 'export-order-column-preferences', scope: 'data-utilities', frequency: 'regular', risk: 'low', presentation: 'text', contract: 'export-order-column-preferences', successOwner: 'orders', failureOwner: 'orders' },
  ],
  states: ['loading', 'slow', 'empty', 'no-permission', 'network-error', 'long-text', 'extreme-value', 'partial-failure', 'success'],
  responsive: { release: ['1366x768', '1280x720'], split: '1024x768', wide: '1920x1080' },
  accessibility: {
    keyboard: ['Reach and operate query, queues, table utilities, row actions, pagination, and every opened overlay in a logical order.'],
    naming: ['Every icon-only command and state-changing control exposes a business-specific accessible name.'],
    zoom: '200%',
  },
  authorities: ['list-page.md', 'filter-layout.md', 'table.md', 'actions.md', 'detail-form.md', 'modal.md', 'overlay-dimensions.md', 'feedback.md', 'responsive.md'],
  verification: ['node scripts/check-spec.js', 'npm run build', 'real-route viewport and state matrix'],
});
