import type { PutawayRecord } from './types';

export const mockPutawayRows: PutawayRecord[] = [
  {
    Id: '1',
    instructionNo: 'JSRK06120001',
    storageOrderNo: 'RC202506120001',
    putawayStatus: '待上架',
    putawayStatusKey: 'wait',
    transportMode: '海运',
    expressNo: '',
    binLocation: '11排-1号',
    putawayDate: '2026-06-12 14:32:18',
    volume: 12.5,
    chargeableWeight: 856,
    chargeableVolume: 13.2,
    warehouse: '东莞金山仓库',
    inspector: 'admin',
    outboundStatus: '未出仓',
    outboundStatusKey: 'draft',
    photoUploaded: false,
    statusTag: 'photoMissing',
  },
  {
    Id: '2',
    instructionNo: 'JSRK06120002',
    storageOrderNo: 'RC202506120002',
    putawayStatus: '上架完成',
    putawayStatusKey: 'rel',
    transportMode: '海运',
    expressNo: 'SF1234567890',
    binLocation: '08排-3号',
    putawayDate: '2026-06-11 09:15:42',
    volume: 8.2,
    chargeableWeight: 520,
    chargeableVolume: 8.6,
    warehouse: '东莞金山仓库',
    inspector: 'zhangsan',
    outboundStatus: '未出仓',
    outboundStatusKey: 'draft',
    photoUploaded: true,
    statusTag: 'normal',
  },
  {
    Id: '3',
    instructionNo: 'JSRK06120003',
    storageOrderNo: 'RC202506110088',
    putawayStatus: '待上架',
    putawayStatusKey: 'wait',
    transportMode: '空运',
    expressNo: '',
    binLocation: '03排-2号',
    putawayDate: '2026-06-10 16:48:05',
    volume: 2.1,
    chargeableWeight: 180,
    chargeableVolume: 2.3,
    warehouse: '深圳宝安仓库',
    inspector: 'lisi',
    outboundStatus: '部分出仓',
    outboundStatusKey: 'partial',
    photoUploaded: false,
    statusTag: 'problem',
  },
  {
    Id: '4',
    instructionNo: 'JSRK06120004',
    storageOrderNo: 'RC202506100045',
    putawayStatus: '上架完成',
    putawayStatusKey: 'rel',
    transportMode: '海运',
    expressNo: 'YT9988776655',
    binLocation: '15排-6号',
    putawayDate: '2026-06-09 11:22:33',
    volume: 18.6,
    chargeableWeight: 1240,
    chargeableVolume: 19.1,
    warehouse: '东莞金山仓库',
    inspector: 'wangwu',
    outboundStatus: '未出仓',
    outboundStatusKey: 'draft',
    photoUploaded: true,
    statusTag: 'expressToTruck',
  },
  {
    Id: '5',
    instructionNo: 'JSRK06120005',
    storageOrderNo: 'RC202506090032',
    putawayStatus: '上架完成',
    putawayStatusKey: 'rel',
    transportMode: '卡派',
    expressNo: '',
    binLocation: '06排-4号',
    putawayDate: '2026-06-08 08:05:17',
    volume: 25.3,
    chargeableWeight: 2100,
    chargeableVolume: 26,
    warehouse: '东莞金山仓库',
    inspector: 'admin',
    outboundStatus: '未出仓',
    outboundStatusKey: 'draft',
    photoUploaded: false,
    statusTag: 'photoMissing',
  },
];
