import { defineFeatureContracts } from '@/design-system/featureContract';

export const QUERY_SCENARIO_FEATURE_CONTRACTS = defineFeatureContracts([
  {
    id: 'query-scenario-apply',
    actorRoles: ['ui.acceptance.viewer'],
    visibleWhen: '当前查询场景包含可应用的查询条件',
    enabledWhen: '查询场景未在应用中',
    request: '在本地验收数据中应用当前场景的可见与高级查询条件',
    successResult: '重置到第一页并更新场景结果表与已应用条件计数',
    errorResult: '保留全部查询条件并在结果表位置显示可恢复错误',
    refreshScope: '当前查询场景、结果表和分页',
  },
  {
    id: 'query-scenario-query-preferences',
    actorRoles: ['ui.acceptance.viewer'],
    visibleWhen: '当前验收场景使用页面与抽屉查询项配置',
    enabledWhen: '页面字段未超过最小宽度容量且没有保存正在执行',
    request: '按场景将稳定查询字段 id 的页面/抽屉归属与顺序保存到本地工作区存储',
    successResult: '立即应用字段归属和顺序，同时保留查询值、结果、分页和表格选择',
    errorResult: '保持设置抽屉打开并保留草稿，显示可恢复的保存错误',
    refreshScope: '当前验收场景的查询字段归属与顺序',
  },
  {
    id: 'query-scenario-refresh',
    actorRoles: ['ui.acceptance.viewer'],
    visibleWhen: '结果表可见',
    enabledWhen: '当前结果表未在查询或刷新中',
    request: '重新读取当前本地验收结果，同时保留已应用查询、页码和列偏好',
    successResult: '保留结果上下文并显示可观察的表格局部刷新完成反馈',
    errorResult: '保留最后可用结果并在结果表位置提供可重试错误',
    refreshScope: '当前结果表',
  },
  {
    id: 'query-scenario-column-preferences',
    actorRoles: ['ui.acceptance.viewer'],
    visibleWhen: '结果表可见',
    enabledWhen: '表格实例已就绪且至少保留四个业务字段',
    request: '将版本化可见字段列表与业务列顺序保存到本地工作区存储',
    successResult: '关闭锚定列设置面板并立即应用真实 VXE 列显隐和排序',
    errorResult: '保留面板与草稿选择并显示具体的就绪或数量错误',
    refreshScope: '当前结果表列显隐、排序与横向布局',
  },
  {
    id: 'query-scenario-status-update',
    actorRoles: ['ui.acceptance.viewer'],
    visibleWhen: '结果行可见',
    enabledWhen: '当前行没有其他本地变更正在执行',
    request: '将当前验收订单推进到确定的下一个本地状态',
    successResult: '更新当前行状态文字和语义色并保留表格上下文',
    errorResult: '保留原状态并在当前行提供可恢复反馈',
    refreshScope: '当前结果行',
  },
  {
    id: 'query-scenario-assign-self',
    actorRoles: ['ui.acceptance.viewer'],
    visibleWhen: '结果行可见',
    enabledWhen: '当前行没有其他本地变更正在执行',
    request: '将当前验收订单负责人更新为当前验收操作员',
    successResult: '更新当前行负责人并保留查询、页码和列偏好',
    errorResult: '保留原负责人并在当前行提供可恢复反馈',
    refreshScope: '当前结果行',
  },
] as const);
