import type { RouteRecordRaw } from 'vue-router';

export const uiAcceptanceRoutes: RouteRecordRaw[] = [
  { path: 'ui-acceptance/design-guide/list-pages', name: 'UiAcceptanceListDesignGuide', component: () => import('@/views/uiAcceptance/listDesignGuide/index.vue'), meta: { menuKey: 'ui-acceptance-list-design-guide', title: '列表设计说明', titleKey: 'routes.uiAcceptanceDesignGuide' } },
  { path: 'ui-acceptance/detail-modules/complex', name: 'DetailModuleComplex', component: () => import('@/views/uiAcceptance/detailModules/index.vue'), meta: { menuKey: 'detail-module-complex', title: '复杂详情模块', titleKey: 'routes.detailModuleComplex' } },
  { path: 'ui-acceptance/interactions/form-overlays', name: 'InteractionFormOverlays', component: () => import('@/views/uiAcceptance/interactionScenarios/index.vue'), props: { initialScenario: 'form-overlays' }, meta: { menuKey: 'interaction-form-overlays', title: '表单与弹窗', titleKey: 'routes.interactionFormOverlays' } },
  { path: 'ui-acceptance/interactions/action-hierarchy', name: 'InteractionActionHierarchy', component: () => import('@/views/uiAcceptance/interactionScenarios/index.vue'), props: { initialScenario: 'action-hierarchy' }, meta: { menuKey: 'interaction-action-hierarchy', title: '按钮与操作', titleKey: 'routes.interactionActionHierarchy' } },
  { path: 'ui-acceptance/interactions/feedback-states', name: 'InteractionFeedbackStates', component: () => import('@/views/uiAcceptance/interactionScenarios/index.vue'), props: { initialScenario: 'feedback-states' }, meta: { menuKey: 'interaction-feedback-states', title: '反馈与状态', titleKey: 'routes.interactionFeedbackStates' } },
  { path: 'ui-acceptance/query-scenarios/s0', name: 'QueryScenarioS0', component: () => import('@/views/uiAcceptance/queryScenarios/index.vue'), props: { initialScenario: 's0' }, meta: { menuKey: 'query-scenario-s0', title: '无查询', titleKey: 'routes.queryS0' } },
  { path: 'ui-acceptance/query-scenarios/s1-compact', name: 'QueryScenarioS1Compact', component: () => import('@/views/uiAcceptance/queryScenarios/index.vue'), props: { initialScenario: 's1-compact' }, meta: { menuKey: 'query-scenario-s1-compact', title: '固定单行紧凑查询', titleKey: 'routes.queryS1Compact' } },
  { path: 'ui-acceptance/query-scenarios/s1-inline', name: 'QueryScenarioS1Inline', component: () => import('@/views/uiAcceptance/queryScenarios/index.vue'), props: { initialScenario: 's1-inline' }, meta: { menuKey: 'query-scenario-s1-inline', title: '固定单行完整查询', titleKey: 'routes.queryS1Inline' } },
  { path: 'ui-acceptance/query-scenarios/s2-expand', name: 'QueryScenarioS2Expand', component: () => import('@/views/uiAcceptance/queryScenarios/index.vue'), props: { initialScenario: 's2-expand' }, meta: { menuKey: 'query-scenario-s2-expand', title: '12项页面抽屉配置', titleKey: 'routes.queryS2Expand' } },
  { path: 'ui-acceptance/query-scenarios/s3-drawer', name: 'QueryScenarioS3Drawer', component: () => import('@/views/uiAcceptance/queryScenarios/index.vue'), props: { initialScenario: 's3-drawer' }, meta: { menuKey: 'query-scenario-s3-drawer', title: '24项页面抽屉配置', titleKey: 'routes.queryS3Drawer' } },
  { path: 'ui-acceptance/query-scenarios/s3-wide', name: 'QueryScenarioS3Wide', component: () => import('@/views/uiAcceptance/queryScenarios/index.vue'), props: { initialScenario: 's3-wide' }, meta: { menuKey: 'query-scenario-s3-wide', title: '40项宽抽屉配置', titleKey: 'routes.queryS3Wide' } },
  { path: 'ui-acceptance/query-scenarios/s4-drawer', name: 'QueryScenarioS4Drawer', component: () => import('@/views/uiAcceptance/queryScenarios/index.vue'), props: { initialScenario: 's4-drawer' }, meta: { menuKey: 'query-scenario-s4-drawer', title: '52项保存查询降级', titleKey: 'routes.queryS4Drawer' } },
  { path: 'ui-acceptance/query-scenarios/s4-workspace', redirect: { name: 'QueryScenarioS4Drawer' } },
];
