import { defineFeatureContracts } from '@/design-system/featureContract';

export const INTERACTION_SCENARIO_FEATURE_CONTRACTS = defineFeatureContracts([
  { id: 'acceptance-contact-save', actorRoles: ['ui.acceptance.reviewer'], visibleWhen: '联系人短表单弹窗可见', enabledWhen: '必填字段有效且未提交', request: '将联系人草稿保存到当前页面本地状态', successResult: '关闭弹窗并刷新联系人摘要', errorResult: '弹窗保持打开，字段值与局部错误保留', refreshScope: '联系人摘要与弹窗' },
  { id: 'acceptance-customer-save', actorRoles: ['ui.acceptance.reviewer'], visibleWhen: '客户资料标准表单弹窗可见', enabledWhen: '必填字段有效且未提交', request: '将客户资料草稿保存到当前页面本地状态', successResult: '关闭弹窗并刷新客户资料摘要', errorResult: '弹窗保持打开，字段值与业务错误保留', refreshScope: '客户资料摘要与弹窗' },
  { id: 'acceptance-settlement-save', actorRoles: ['ui.acceptance.reviewer'], visibleWhen: '结算资料大表单弹窗可见', enabledWhen: '必填字段有效且未提交', request: '将结算资料草稿保存到当前页面本地状态', successResult: '关闭弹窗并刷新结算资料摘要', errorResult: '弹窗保持打开，字段值与业务错误保留', refreshScope: '结算资料摘要与弹窗' },
  { id: 'acceptance-task-create', actorRoles: ['ui.acceptance.reviewer'], visibleWhen: '操作层级场景可见且拥有创建权限', enabledWhen: '没有创建任务正在提交', request: '向本地任务列表插入一条新任务', successResult: '新任务出现在列表首行', errorResult: '保留当前列表与选择上下文并显示局部错误', refreshScope: '任务列表和分页' },
  { id: 'acceptance-task-progress', actorRoles: ['ui.acceptance.reviewer'], visibleWhen: '当前任务允许推进', enabledWhen: '当前行没有其他操作进行中', request: '推进当前本地任务到下一状态', successResult: '更新当前行状态、下一动作和更新时间', errorResult: '保持当前行状态并显示可重试反馈', refreshScope: '当前任务行' },
  { id: 'acceptance-task-assign', actorRoles: ['ui.acceptance.reviewer'], visibleWhen: '当前任务允许分配', enabledWhen: '当前行没有其他操作进行中', request: '将当前本地任务负责人改为 admin', successResult: '更新当前行负责人和更新时间', errorResult: '保持当前负责人并显示可重试反馈', refreshScope: '当前任务行' },
  { id: 'acceptance-task-batch', actorRoles: ['ui.acceptance.reviewer'], visibleWhen: '批量操作按钮可见', enabledWhen: '至少选择一条可推进任务且没有批量请求进行中', request: '推进所选本地任务，部分失败场景按稳定规则返回失败项', successResult: '成功行更新并取消选择，失败行保持选择', errorResult: '失败行保持选择并在表格上方显示原因与重试入口', refreshScope: '选择状态、任务行与批量反馈' },
  { id: 'acceptance-task-download', actorRoles: ['ui.acceptance.reviewer'], visibleWhen: '当前任务 More 菜单可见', enabledWhen: '当前任务不存在其他行操作', request: '生成当前本地任务的演示下载结果', successResult: '显示包含任务编号的下载成功反馈', errorResult: '保持当前任务和列表上下文', refreshScope: '下载结果，不刷新列表' },
  { id: 'acceptance-task-refresh', actorRoles: ['ui.acceptance.reviewer'], visibleWhen: '任务表格工具栏可见', enabledWhen: '列表没有刷新请求进行中', request: '重新读取当前页面本地任务状态', successResult: '保留选择和列表位置并显示刷新结果', errorResult: '保留当前可用任务与上下文', refreshScope: '任务表格' },
  { id: 'acceptance-task-delete', actorRoles: ['ui.acceptance.reviewer'], visibleWhen: '当前任务 More 菜单可见且拥有删除权限', enabledWhen: '用户已确认删除影响', request: '从本地任务列表删除当前任务', successResult: '移除当前行并修正分页', errorResult: '保留当前行和列表上下文', refreshScope: '任务列表、分页和选择状态' },
  { id: 'acceptance-document-submit', actorRoles: ['ui.acceptance.reviewer'], visibleWhen: '资料校验状态可见', enabledWhen: '必填字段有效且未提交', request: '校验并提交当前本地补料资料', successResult: '资料状态更新并显示提交结果', errorResult: '字段错误留在对应表单项并保留输入', refreshScope: '资料表单与状态' },
  { id: 'acceptance-feedback-download', actorRoles: ['ui.acceptance.reviewer'], visibleWhen: '成功或长文本反馈状态可见', enabledWhen: '资料结果可下载', request: '生成当前本地资料结果的演示下载反馈', successResult: '显示资料下载成功反馈', errorResult: '保持当前资料状态', refreshScope: '下载结果，不刷新工作面' },
  { id: 'acceptance-feedback-retry', actorRoles: ['ui.acceptance.reviewer'], visibleWhen: '反馈场景处于可恢复失败状态', enabledWhen: '没有重试请求进行中', request: '将当前本地反馈场景恢复为成功状态', successResult: '保留业务上下文并重新显示可用内容', errorResult: '保持错误状态与重试入口', refreshScope: '反馈场景工作面' },
] as const);
