import { definePesdpPageSpec } from '../../../design-system/pesdpPageSpec';

export const INTERACTION_SCENARIO_PAGE_SPEC = definePesdpPageSpec({
  id: 'ui-acceptance-interaction-scenarios',
  target: 'strong-internal-product',
  archetype: 'list-management',
  input: {
    path: 'requirement',
    artifacts: ['project UI/UX acceptance requirement for modules, overlays, forms, buttons, actions, and feedback'],
    unresolvedBusinessDecisions: ['backend persistence, production permission keys, and audit APIs are intentionally outside this frontend-only acceptance surface'],
    recommendations: ['use deterministic local scenarios to approve UI contracts before connecting production APIs'],
  },
  list: {
    frame: 'standard-list-v1',
    profile: 'management',
    commandSurface: 'compact',
    tableTop: 'utility-cap',
    selection: 'conditional',
    workScope: 'none',
    statusQueues: 'none',
    views: {
      pageMode: 'segmented',
      pageModeCount: 3,
      workflowState: 'none',
      workflowStateCount: 0,
      workflowStatePlacement: 'none',
      workflowStateOverflow: 'none',
    },
  },
  business: {
    object: 'ui-interaction-acceptance-scenario',
    primaryUser: 'product-and-ui-acceptance-reviewer',
    userJob: 'exercise-complete-form-overlay-action-and-feedback-contracts-before-production-integration',
    primaryIdentity: ['scenarioName'],
    keyState: ['uiState', 'permissionState', 'pendingState'],
    mainWorkingData: ['customerDraft', 'shipmentTasks', 'documentFeedback'],
    supportingData: ['validationResult', 'partialFailureResult', 'longContent'],
  },
  pesdp: {
    professional: {
      decisions: ['Use customer maintenance, shipment task processing, and document supplementation as credible business contexts for interaction acceptance.'],
      acceptance: ['Every control uses object-specific labels and produces an observable local business result.'],
    },
    efficient: {
      decisions: ['Expose each acceptance scenario as a routed menu entry while reusing one stable page-mode workbench.'],
      acceptance: ['Reviewers can open any scenario directly and reproduce its normal and adverse states without setup.'],
    },
    structured: {
      decisions: ['Keep one page-mode owner, one scenario toolbar, one work surface, and owner-local feedback.'],
      acceptance: ['No action, total, state, or error is duplicated across page and overlay scopes.'],
    },
    dense: {
      decisions: ['Use compact Arco forms and controls, tiered overlays, and the global mini VXE table for the row-action scenario.'],
      acceptance: ['The primary work surface remains usable at 1024x768 and overlays have no internal horizontal overflow.'],
    },
    premium: {
      decisions: ['Use GI-native component states, semantic status pills, restrained action hierarchy, and deterministic recovery paths.'],
      acceptance: ['Validation, permission, network, slow, long-content, and partial-failure states remain visually coherent and recoverable.'],
    },
  },
  surfaces: [
    { id: 'scenario-mode', role: 'identity', owns: ['active-scenario', 'scenario-route'], implementation: 'arco' },
    { id: 'scenario-toolbar', role: 'command', owns: ['scenario-state', 'business-actions', 'selection-context'], implementation: 'arco' },
    { id: 'scenario-work-surface', role: 'data', owns: ['business-preview', 'table-data', 'owner-local-feedback'], implementation: 'shared-pattern', whyArcoNotEnough: 'The standard list frame and VXE baseline keep acceptance evidence comparable to real routed pages.' },
    { id: 'scenario-overlays', role: 'supporting', owns: ['confirm-modal', 'short-form-modal', 'standard-form-modal', 'large-form-modal'], implementation: 'arco' },
  ],
  query: { totalFields: 0, strategy: 'none', layout: 'none', visibleFields: [], visibleFieldLayout: [], advancedFields: [] },
  table: {
    kind: 'management-list',
    rowBanding: 'striped',
    identityColumns: ['sequence', 'taskNo', 'taskState'],
    decisionColumns: ['customer', 'owner', 'nextAction'],
    supportingColumns: ['updatedAt'],
    fixed: ['taskNo', 'operations'],
    densityReason: 'The action scenario must prove table-row hierarchy in the same high-density baseline as production lists.',
  },
  detail: { mode: 'none', focus: [], milestones: [] },
  actions: [
    { id: 'acceptance-contact-save', scope: 'short-form-modal', frequency: 'regular', risk: 'low', presentation: 'primary', contract: 'acceptance-contact-save', successOwner: 'scenario-work-surface', failureOwner: 'scenario-overlays' },
    { id: 'acceptance-customer-save', scope: 'standard-form-modal', frequency: 'regular', risk: 'low', presentation: 'primary', contract: 'acceptance-customer-save', successOwner: 'scenario-work-surface', failureOwner: 'scenario-overlays' },
    { id: 'acceptance-settlement-save', scope: 'large-form-modal', frequency: 'regular', risk: 'medium', presentation: 'primary', contract: 'acceptance-settlement-save', successOwner: 'scenario-work-surface', failureOwner: 'scenario-overlays' },
    { id: 'acceptance-task-create', scope: 'scenario-toolbar', frequency: 'daily', risk: 'low', presentation: 'primary', contract: 'acceptance-task-create', successOwner: 'scenario-work-surface', failureOwner: 'scenario-work-surface' },
    { id: 'acceptance-task-progress', scope: 'row', frequency: 'daily', risk: 'low', presentation: 'row-action', contract: 'acceptance-task-progress', successOwner: 'scenario-work-surface', failureOwner: 'scenario-work-surface' },
    { id: 'acceptance-task-assign', scope: 'row', frequency: 'daily', risk: 'low', presentation: 'row-action', contract: 'acceptance-task-assign', successOwner: 'scenario-work-surface', failureOwner: 'scenario-work-surface' },
    { id: 'acceptance-task-batch', scope: 'scenario-toolbar', frequency: 'regular', risk: 'medium', presentation: 'outline', contract: 'acceptance-task-batch', successOwner: 'scenario-work-surface', failureOwner: 'scenario-work-surface' },
    { id: 'acceptance-task-download', scope: 'row', frequency: 'regular', risk: 'low', presentation: 'dropdown', contract: 'acceptance-task-download', successOwner: 'scenario-work-surface', failureOwner: 'scenario-work-surface' },
    { id: 'acceptance-task-refresh', scope: 'scenario-toolbar', frequency: 'regular', risk: 'low', presentation: 'text', contract: 'acceptance-task-refresh', successOwner: 'scenario-work-surface', failureOwner: 'scenario-work-surface' },
    { id: 'acceptance-task-delete', scope: 'row', frequency: 'rare', risk: 'high', presentation: 'dropdown', contract: 'acceptance-task-delete', successOwner: 'scenario-work-surface', failureOwner: 'scenario-work-surface' },
    { id: 'acceptance-document-submit', scope: 'scenario-work-surface', frequency: 'regular', risk: 'low', presentation: 'primary', contract: 'acceptance-document-submit', successOwner: 'scenario-work-surface', failureOwner: 'scenario-work-surface' },
    { id: 'acceptance-feedback-download', scope: 'scenario-work-surface', frequency: 'regular', risk: 'low', presentation: 'outline', contract: 'acceptance-feedback-download', successOwner: 'scenario-work-surface', failureOwner: 'scenario-work-surface' },
    { id: 'acceptance-feedback-retry', scope: 'scenario-work-surface', frequency: 'regular', risk: 'low', presentation: 'text', contract: 'acceptance-feedback-retry', successOwner: 'scenario-work-surface', failureOwner: 'scenario-work-surface' },
  ],
  states: ['loading', 'slow', 'empty', 'no-permission', 'validation-error', 'business-error', 'network-error', 'partial-failure', 'long-data', 'success'],
  responsive: { release: ['1366x768'], split: '1024x768', wide: '1920x1080' },
  accessibility: {
    keyboard: ['Reach page mode, scenario state, business actions, table rows, overlay fields, confirmation actions, and recovery controls in workflow order.'],
    naming: ['Every icon-only utility and More trigger exposes a business-specific accessible name.'],
    zoom: '200%',
  },
  authorities: ['list-page.md', 'table.md', 'modal.md', 'overlay-dimensions.md', 'form-rules.md', 'actions.md', 'feedback.md', 'permissions.md'],
  verification: ['node scripts/check-spec.js', 'npm run build', 'three real routes at 1024x768, 1366x768, 1920x1080, and 200% zoom with deterministic state evidence'],
});
