import type { ProfitRecord } from './types';

export const mockProfitRows: ProfitRecord[] = [
  {
    Id: '1',
    orderNo: 'PTP2025060001',
    company: '深圳点达',
    businessScope: '海运出口',
    mbl: 'COSU6288888',
    customer: '深圳某某贸易',
    containerSummary: '1×40HQ',
    grossWeight: 18500,
    volume: 58.2,
    transportMode: '海运',
    pol: 'CNSZX',
    pod: 'USLAX',
    realProfit: 418.85,
    realEstimate: 418.85,
    salesAmount: 28600,
    currency: 'CNY',
    orderStatus: '已放舱',
    orderStatusKey: 'rel',
    etd: '2026-06-12',
    eta: '2026-07-08',
    fobCs: 'zhangsan',
    docCs: 'wangwu',
    placeOfReceipt: '深圳',
    invoiceMarked: false,
  },
  {
    Id: '2',
    orderNo: 'PTP2025060002',
    company: '深圳点达',
    businessScope: '海运出口',
    mbl: 'OOLU8899001',
    customer: '广州华南物流',
    containerSummary: '2×20GP',
    grossWeight: 9200,
    volume: 32.5,
    transportMode: '海运',
    pol: 'CNYTN',
    pod: 'DEHAM',
    realProfit: 634.6,
    realEstimate: 3184,
    salesAmount: 45200,
    currency: 'CNY',
    orderStatus: '操作中',
    orderStatusKey: 'op',
    etd: '2026-06-18',
    eta: '2026-08-02',
    fobCs: 'lisi',
    docCs: 'admin',
    placeOfReceipt: '广州',
    invoiceMarked: true,
  },
  {
    Id: '3',
    orderNo: 'PTP2025060003',
    company: '上海分公司',
    businessScope: '空运出口',
    mbl: '784-12345678',
    customer: '上海科技股份',
    containerSummary: '—',
    grossWeight: 850,
    volume: 4.2,
    transportMode: '空运',
    pol: 'CNPVG',
    pod: 'JPNRT',
    realProfit: 1205.3,
    realEstimate: 1205.3,
    salesAmount: 12800,
    currency: 'CNY',
    orderStatus: '已完成',
    orderStatusKey: 'acc',
    etd: '2026-06-05',
    eta: '2026-06-09',
    fobCs: 'zhangsan',
    docCs: 'admin',
    placeOfReceipt: '上海',
    invoiceMarked: true,
  },
  {
    Id: '4',
    orderNo: 'PTP2025060004',
    company: '深圳点达',
    businessScope: '海运进口',
    mbl: 'MAEU5566778',
    customer: '东莞制造有限公司',
    containerSummary: '1×40GP',
    grossWeight: 14200,
    volume: 45.0,
    transportMode: '海运',
    pol: 'SGSIN',
    pod: 'CNSZX',
    realProfit: -86.5,
    realEstimate: 220,
    salesAmount: 19800,
    currency: 'CNY',
    orderStatus: '待确认',
    orderStatusKey: 'wait',
    etd: '2026-06-25',
    eta: '2026-07-15',
    fobCs: 'lisi',
    docCs: 'wangwu',
    placeOfReceipt: '东莞',
    invoiceMarked: false,
  },
  {
    Id: '5',
    orderNo: 'PTP2025060005',
    company: '宁波办事处',
    businessScope: '海运出口',
    mbl: 'HLCU9988776',
    customer: '宁波进出口',
    containerSummary: '3×40HQ',
    grossWeight: 52000,
    volume: 168.0,
    transportMode: '海运',
    pol: 'CNNGB',
    pod: 'NLRTM',
    realProfit: 2890.15,
    realEstimate: 3100,
    salesAmount: 98600,
    currency: 'CNY',
    orderStatus: '已放舱',
    orderStatusKey: 'rel',
    etd: '2026-06-20',
    eta: '2026-08-10',
    fobCs: 'zhangsan',
    docCs: 'wangwu',
    placeOfReceipt: '宁波',
    invoiceMarked: false,
  },
];
