import type { StatementRecord } from './types';

export const mockStatementRows: StatementRecord[] = [
  {
    Id: '1',
    type: '应收',
    contractUnit: '深圳某某贸易有限公司',
    salesperson: '张三',
    department: '销售一部',
    totalBillAmount: 186520.5,
    unwrittenOffAmount: 45200,
    overdueAmount: 12800,
    estimatedPaymentDate: '2026-07-15',
    estimatedPaymentAmount: 45200,
    estimatedPaymentCurrency: 'CNY',
    remark: '月结对账',
  },
  {
    Id: '2',
    type: '应付',
    contractUnit: 'COSCO SHIPPING LINES',
    salesperson: '李四',
    department: '操作二组',
    totalBillAmount: 98400,
    unwrittenOffAmount: 98400,
    overdueAmount: 0,
    estimatedPaymentDate: '2026-07-20',
    estimatedPaymentAmount: 98400,
    estimatedPaymentCurrency: 'USD',
    remark: '',
    missingAtd: true,
  },
  {
    Id: '3',
    type: '应收',
    contractUnit: '广州华南物流有限公司',
    salesperson: '王五',
    department: '销售二部',
    totalBillAmount: 328600,
    unwrittenOffAmount: 0,
    overdueAmount: 0,
    estimatedPaymentDate: '2026-06-28',
    estimatedPaymentAmount: 0,
    estimatedPaymentCurrency: 'CNY',
    remark: '已结清',
  },
  {
    Id: '4',
    type: '应收',
    contractUnit: '宁波港务进出口',
    salesperson: '赵六',
    department: '销售三部',
    totalBillAmount: 76200.8,
    unwrittenOffAmount: 32100.8,
    overdueAmount: 5600,
    estimatedPaymentDate: '2026-08-01',
    estimatedPaymentAmount: 32100.8,
    estimatedPaymentCurrency: 'CNY',
    remark: '部分核销',
  },
];
