import type { CustomerRecord } from './types';

export const mockCustomers: CustomerRecord[] = [
  {
    Id: '1',
    name: '深圳某某科技有限公司',
    customerType: '直客',
    country: '中国',
    tags: [
      { label: '转介绍', tone: 'rel' },
      { label: '待开发', tone: 'wait' },
    ],
    csName: '张三',
    contactName: '王经理',
    contactEmail: 'wang@example.com',
    contactPhone: '13800138001',
    contactTitle: '采购总监',
    lastFollowUp: '2026-06-20 电话沟通，客户对欧线报价感兴趣',
    cooperateStatus: 'uncooperated',
    deleted: false,
    createdAt: '2026-01-15',
    lastFollowAt: '2026-06-20',
    lastShipAt: '',
    opsStaff: '李四',
    creator: 'admin',
    remark: '重点跟进欧线业务',
  },
  {
    Id: '2',
    name: '广州华南贸易有限公司',
    customerType: '同行',
    country: '中国',
    tags: [{ label: 'VIP', tone: 'acc' }],
    csName: '李四',
    contactName: '陈总',
    contactEmail: 'chen@hn-trade.com',
    contactPhone: '13900139002',
    contactTitle: '总经理',
    lastFollowUp: '2026-06-18 已确认美西航线合作条款',
    cooperateStatus: 'cooperated',
    deleted: false,
    createdAt: '2025-08-10',
    lastFollowAt: '2026-06-18',
    lastShipAt: '2026-06-10',
    opsStaff: '王五',
    creator: 'zhangsan',
    remark: '',
  },
  {
    Id: '3',
    name: 'Hamburg Logistics GmbH',
    customerType: '海外代理',
    country: '德国',
    tags: [
      { label: '欧线', tone: 'op' },
      { label: '长期合作', tone: 'rel' },
    ],
    csName: '王五',
    contactName: 'Hans Mueller',
    contactEmail: 'hans@hamburg-log.de',
    contactPhone: '+49-40-123456',
    contactTitle: 'Director',
    lastFollowUp: '2026-06-15 Quarterly review meeting completed',
    cooperateStatus: 'cooperated',
    deleted: false,
    createdAt: '2024-03-22',
    lastFollowAt: '2026-06-15',
    lastShipAt: '2026-05-28',
    opsStaff: '赵六',
    creator: 'lisi',
    remark: '德线核心代理',
  },
  {
    Id: '4',
    name: '宁波港城进出口有限公司',
    customerType: '直客',
    country: '中国',
    tags: [{ label: '新线索', tone: 'draft' }],
    csName: '张三',
    contactName: '刘小姐',
    contactEmail: 'liu@nb-port.com',
    contactPhone: '13700137004',
    contactTitle: '业务经理',
    lastFollowUp: '2026-06-22 发送了东南亚航线报价单',
    cooperateStatus: 'uncooperated',
    deleted: false,
    createdAt: '2026-05-01',
    lastFollowAt: '2026-06-22',
    lastShipAt: '',
    opsStaff: '',
    creator: 'zhangsan',
    remark: '',
  },
  {
    Id: '5',
    name: '上海东方国际货运代理',
    customerType: '同行',
    country: '中国',
    tags: [{ label: '华东', tone: 'op' }],
    csName: '李四',
    contactName: '周经理',
    contactEmail: 'zhou@east-intl.com',
    contactPhone: '13600136005',
    contactTitle: '操作主管',
    lastFollowUp: '2026-06-12 处理拼箱业务异常',
    cooperateStatus: 'cooperated',
    deleted: false,
    createdAt: '2025-11-08',
    lastFollowAt: '2026-06-12',
    lastShipAt: '2026-06-08',
    opsStaff: '李四',
    creator: 'admin',
    remark: '',
  },
  {
    Id: '6',
    name: 'Los Angeles Freight Co.',
    customerType: '海外代理',
    country: '美国',
    tags: [
      { label: '美西', tone: 'partial' },
      { label: '待报价', tone: 'wait' },
    ],
    csName: '王五',
    contactName: 'John Smith',
    contactEmail: 'john@la-freight.com',
    contactPhone: '+1-310-555-0100',
    contactTitle: 'Sales Manager',
    lastFollowUp: '2026-06-10 Sent updated rate sheet',
    cooperateStatus: 'uncooperated',
    deleted: false,
    createdAt: '2026-03-18',
    lastFollowAt: '2026-06-10',
    lastShipAt: '',
    opsStaff: '赵六',
    creator: 'lisi',
    remark: '美西潜在代理',
  },
  {
    Id: '7',
    name: '厦门海韵电子有限公司',
    customerType: '直客',
    country: '中国',
    tags: [{ label: '电子产品', tone: 'acc' }],
    csName: '张三',
    contactName: '林工',
    contactEmail: 'lin@haiyun-elec.com',
    contactPhone: '13500135007',
    contactTitle: '物流专员',
    lastFollowUp: '2026-06-25 确认下月出货计划',
    cooperateStatus: 'cooperated',
    deleted: false,
    createdAt: '2025-06-20',
    lastFollowAt: '2026-06-25',
    lastShipAt: '2026-06-20',
    opsStaff: '王五',
    creator: 'zhangsan',
    remark: 'FBA 主力客户',
  },
  {
    Id: '8',
    name: '天津渤海航运服务有限公司',
    customerType: '同行',
    country: '中国',
    tags: [],
    csName: '李四',
    contactName: '孙主任',
    contactEmail: 'sun@bohai-ship.com',
    contactPhone: '13400134008',
    contactTitle: '市场部经理',
    lastFollowUp: '2026-05-30 暂停合作洽谈',
    cooperateStatus: 'uncooperated',
    deleted: true,
    createdAt: '2025-02-14',
    lastFollowAt: '2026-05-30',
    lastShipAt: '2025-12-01',
    opsStaff: '',
    creator: 'admin',
    remark: '已删除归档',
  },
  {
    Id: '9',
    name: 'Bangkok Express Logistics',
    customerType: '海外代理',
    country: '泰国',
    tags: [{ label: '东南亚', tone: 'op' }],
    csName: '王五',
    contactName: 'Somchai',
    contactEmail: 'somchai@bk-express.th',
    contactPhone: '+66-2-123-4567',
    contactTitle: 'GM',
    lastFollowUp: '2026-06-08 泰线拼箱报价跟进',
    cooperateStatus: 'cooperated',
    deleted: false,
    createdAt: '2024-09-05',
    lastFollowAt: '2026-06-08',
    lastShipAt: '2026-05-15',
    opsStaff: '赵六',
    creator: 'lisi',
    remark: '',
  },
  {
    Id: '10',
    name: '青岛远洋制造集团',
    customerType: '直客',
    country: '中国',
    tags: [
      { label: '大件货', tone: 'partial' },
      { label: '重点项目', tone: 'wait' },
    ],
    csName: '张三',
    contactName: '马总',
    contactEmail: 'ma@qd-ocean.com',
    contactPhone: '13300133010',
    contactTitle: '副总裁',
    lastFollowUp: '2026-06-28 项目投标方案讨论',
    cooperateStatus: 'uncooperated',
    deleted: false,
    createdAt: '2026-02-28',
    lastFollowAt: '2026-06-28',
    lastShipAt: '',
    opsStaff: '李四',
    creator: 'zhangsan',
    remark: '年度大单潜在',
  },
  {
    Id: '11',
    name: '武汉长江供应链有限公司',
    customerType: '直客',
    country: '中国',
    tags: [{ label: '内贸转出口', tone: 'draft' }],
    csName: '李四',
    contactName: '何经理',
    contactEmail: 'he@cj-supply.com',
    contactPhone: '13200132011',
    contactTitle: '运营总监',
    lastFollowUp: '2026-06-14 首次拜访完成',
    cooperateStatus: 'uncooperated',
    deleted: false,
    createdAt: '2026-04-10',
    lastFollowAt: '2026-06-14',
    lastShipAt: '',
    opsStaff: '',
    creator: 'admin',
    remark: '',
  },
  {
    Id: '12',
    name: 'Rotterdam Forwarding BV',
    customerType: '海外代理',
    country: '荷兰',
    tags: [{ label: '欧线', tone: 'rel' }],
    csName: '王五',
    contactName: 'Pieter van Dijk',
    contactEmail: 'pieter@rtd-fwd.nl',
    contactPhone: '+31-10-9876543',
    contactTitle: 'Operations Head',
    lastFollowUp: '2026-06-05 Monthly volume review',
    cooperateStatus: 'cooperated',
    deleted: false,
    createdAt: '2023-12-01',
    lastFollowAt: '2026-06-05',
    lastShipAt: '2026-06-01',
    opsStaff: '赵六',
    creator: 'lisi',
    remark: '',
  },
];
