import { defineFeatureContracts } from '@/design-system/featureContract';
import type { ExportUiScenario } from '@/views/uiAcceptance/exportOrderList/types';

const SUPPORTED_UI_SCENARIOS = new Set<ExportUiScenario>([
  'normal',
  'loading',
  'slow',
  'empty',
  'error',
  'permission',
  'partial',
  'long',
  'extreme',
]);

export const resolveExportUiScenario = (value: unknown): ExportUiScenario => {
  if (typeof value !== 'string') return 'normal';
  return SUPPORTED_UI_SCENARIOS.has(value as ExportUiScenario)
    ? value as ExportUiScenario
    : 'normal';
};

export const UA_EXPORT_ORDER_FEATURE_CONTRACTS = defineFeatureContracts([
  {
    id: 'ua-export-order-query',
    actorRoles: ['exportOrder.operator', 'exportOrder.cs', 'exportOrder.document', 'exportOrder.finance', 'exportOrder.manager', 'exportOrder.agent'],
    visibleWhen: 'actor has export-order list read permission',
    enabledWhen: 'page is not loading and query values are valid',
    request: 'GET export orders with the applied page and drawer conditions, ownership scope, queue key, sort, and page; draft edits never trigger it',
    successResult: 'replace the result set, reset pagination to the first page, keep the applied conditions distinguishable from drafts, and refresh queue counts',
    errorResult: 'keep every condition, queue, and page, render a table-local recoverable error with retry, and never impersonate a permission denial',
    refreshScope: 'result table, queue counts, pagination, and selection context',
  },
  {
    id: 'ua-export-order-query-preferences',
    actorRoles: ['exportOrder.operator', 'exportOrder.cs', 'exportOrder.document', 'exportOrder.finance', 'exportOrder.manager', 'exportOrder.agent'],
    visibleWhen: 'the export-order query surface is visible',
    enabledWhen: 'the query field catalog is available, placement fits the two-row page capacity, and no preference save is in flight',
    request: 'persist a versioned ordered partition of stable query-field ids into page and drawer locations in local workspace storage; no query request',
    successResult: 'close the settings drawer and apply the page and drawer order immediately without changing query values, pagination, or selection',
    errorResult: 'keep the settings drawer open, retain the draft placement, and show a specific save failure',
    refreshScope: 'query field placement and order only',
  },
  {
    id: 'ua-export-order-saved-schemes',
    actorRoles: ['exportOrder.operator', 'exportOrder.cs', 'exportOrder.document', 'exportOrder.finance', 'exportOrder.manager'],
    visibleWhen: 'the export-order query surface is visible',
    enabledWhen: 'a scheme name is non-empty and unique, or a scheme target exists for rename, delete, set-default, and reorder; switching schemes must resolve unapplied query changes before applying the target; no save is in flight',
    request: 'persist named snapshots of the currently applied conditions with default flag and order into versioned local workspace storage; invalid stored data falls back to defaults',
    successResult: 'apply the scheme list change immediately; selecting a scheme resolves unapplied query changes explicitly, then replaces the applied conditions, runs the query, and returns to the first page',
    errorResult: 'keep the scheme manager open with the draft intact and show a specific save failure',
    refreshScope: 'scheme list and, when a scheme is applied, the applied query conditions and result table',
  },
  {
    id: 'ua-export-order-import',
    actorRoles: ['exportOrder.operator', 'exportOrder.manager'],
    visibleWhen: 'actor has export-order create permission',
    enabledWhen: 'a template file or pasted rows have been parsed and no import with the same idempotency key is in flight; duplicate submits are intercepted',
    request: 'download template, parse uploaded or pasted rows locally, preview total/importable/error counts with per-row field reasons, then confirm the import once',
    successResult: 'insert importable rows, keep failed rows identifiable with downloadable detail, allow retrying only the failed part, and refresh table and queue counts',
    errorResult: 'keep the import wizard open at the current step with parsed rows and error annotations preserved',
    refreshScope: 'workbench rows, queue counts, and import result summary',
  },
  {
    id: 'ua-export-order-export',
    actorRoles: ['exportOrder.operator', 'exportOrder.cs', 'exportOrder.document', 'exportOrder.finance', 'exportOrder.manager'],
    visibleWhen: 'actor has export permission and the result set is not in an error or permission state',
    enabledWhen: 'no export task is in flight',
    request: 'start an asynchronous export of the current applied result set with the currently visible columns; sensitive fields never enter the artifact under field-permission scenarios',
    successResult: 'notify completion without blocking the page and deliver the CSV with the exported row count',
    errorResult: 'notify the export failure without touching the query, page, or selection context',
    refreshScope: 'no data refresh; export task feedback and download artifact only',
  },
  {
    id: 'ua-export-order-batch',
    actorRoles: ['exportOrder.operator', 'exportOrder.manager'],
    visibleWhen: 'actor has batch permission and at least one row is selected',
    enabledWhen: 'selection is non-empty and no batch request with the same idempotency key is in flight; repeated clicks while pending are intercepted',
    request: 'pre-check mixed eligibility and list skipped rows with reasons for confirmation, then POST the eligible stable ids with the action payload',
    successResult: 'report exact success, partial-failure, or all-failure counts, keep failed rows selected, and offer a downloadable failure detail (order no + reason)',
    errorResult: 'keep the selection and page context, show the failure beside the table, and never silently drop skipped rows',
    refreshScope: 'affected rows, queue counts, selection context, and the batch result summary',
  },
  {
    id: 'ua-export-order-quick-view',
    actorRoles: ['exportOrder.operator', 'exportOrder.cs', 'exportOrder.document', 'exportOrder.finance', 'exportOrder.manager', 'exportOrder.agent'],
    visibleWhen: 'the order row is readable under data permission',
    enabledWhen: 'always; it is a read-only view intent',
    request: 'open the order summary, risk module, recent nodes, and recent activity in a right drawer without a list request',
    successResult: 'render the summary beside the list and restore query, page, and selection context unchanged on close',
    errorResult: 'not applicable; missing data renders as explicit empty sections instead of an error overlay',
    refreshScope: 'no list refresh; quick-view content only',
  },
  {
    id: 'ua-export-order-status-transition',
    actorRoles: ['exportOrder.operator', 'exportOrder.manager'],
    visibleWhen: 'the order is not completed or cancelled and actor has transition permission',
    enabledWhen: 'the target is a legal next state from the transition matrix, a reason is present, and the captured revision still matches',
    request: 'POST status transition with order id, current revision, target, and reason; cancellation additionally requires the receivable and high-exception preconditions and a second confirmation',
    successResult: 'update the row status, append a node and audit log, refresh affected queue counts, and keep the list context',
    errorResult: 'keep the modal open with target and reason preserved; business rejection names the allowed next steps, the cancel blockers, or the stale revision',
    refreshScope: 'current row, affected queue counts, and audit log',
  },
  {
    id: 'ua-export-order-assign',
    actorRoles: ['exportOrder.operator', 'exportOrder.manager'],
    visibleWhen: 'the order is readable and actor has assignment permission',
    enabledWhen: 'an operator is selected and the row is not carrying another mutation',
    request: 'assign one or more orders to the chosen operator using stable ids and revisions',
    successResult: 'update the row owner, keep the current query, queue, and page, and append an assignment audit log',
    errorResult: 'keep the modal open with the selected operator preserved and expose a retryable assignment error',
    refreshScope: 'affected rows and audit log only',
  },
  {
    id: 'ua-export-order-mark-exception',
    actorRoles: ['exportOrder.operator', 'exportOrder.cs', 'exportOrder.manager'],
    visibleWhen: 'the order is not cancelled and actor has exception-report permission',
    enabledWhen: 'type, level, description, owner, and expected resolve time are present and no exception-create request for the same order is in flight',
    request: 'POST exception payload (type, level, description, owner, expected resolve time) with order id and current revision',
    successResult: 'close the modal, mark the order exception open with its level, surface the risk flag, and add the order to the exception queue',
    errorResult: 'keep the modal open with every entered value preserved; localize field errors and expose retry on confirm',
    refreshScope: 'current row exception state and risk flags, exception queue count, and audit log',
  },
  {
    id: 'ua-export-order-generate-fee',
    actorRoles: ['exportOrder.operator', 'exportOrder.finance', 'exportOrder.manager'],
    visibleWhen: 'the order is active and actor has fee-maintenance permission',
    enabledWhen: 'fees are not already generated and the row is not carrying another mutation',
    request: 'create pending fee lines for the order using its stable id and revision',
    successResult: 'move the row fee state to pending, keep it in the fee-unconfirmed queue, and append an audit log',
    errorResult: 'keep the previous fee state and expose a row-owned retryable fee error',
    refreshScope: 'current row fee state and fee queue count',
  },
  {
    id: 'ua-export-order-notify',
    actorRoles: ['exportOrder.operator', 'exportOrder.cs', 'exportOrder.manager'],
    visibleWhen: 'actor has customer-notification permission',
    enabledWhen: 'the row is not carrying another mutation',
    request: 'send the configured order progress notification for the stable order id',
    successResult: 'confirm the notification and append a notification audit log without changing list position or selection',
    errorResult: 'keep the row unchanged and expose a retryable notification error',
    refreshScope: 'audit log only',
  },
  {
    id: 'ua-export-order-upload-file',
    actorRoles: ['exportOrder.operator', 'exportOrder.cs', 'exportOrder.document', 'exportOrder.manager', 'exportOrder.agent'],
    visibleWhen: 'the order is active and actor has file-upload permission',
    enabledWhen: 'a local file is chosen and no upload for the same order is in flight',
    request: 'attach the chosen file to the order through the shared upload boundary; no raw a-upload is used',
    successResult: 'move a missing file state to pending-confirmation, refresh the file queue counts, and append a file audit log',
    errorResult: 'keep the modal open with the chosen file preserved and expose a retryable upload error',
    refreshScope: 'current row file state, file queue counts, and audit log',
  },
  {
    id: 'ua-export-order-copy',
    actorRoles: ['exportOrder.operator', 'exportOrder.manager'],
    visibleWhen: 'actor has export-order create permission and the source order is readable',
    enabledWhen: 'no copy request for the same source order is in flight',
    request: 'create a local draft copy with a newly generated order number derived from the source order',
    successResult: 'insert the copied draft next to the source in the workbench, show the new order number, and refresh queue counts',
    errorResult: 'keep the workbench unchanged and show the copy failure beside the row action',
    refreshScope: 'workbench rows and queue counts only',
  },
  {
    id: 'ua-export-order-view-log',
    actorRoles: ['exportOrder.operator', 'exportOrder.cs', 'exportOrder.document', 'exportOrder.finance', 'exportOrder.manager'],
    visibleWhen: 'the order row is readable under data permission; internal logs stay hidden from the overseas-agent role',
    enabledWhen: 'always; it is a read-only view intent',
    request: 'open the quick-view drawer focused on the recent activity module',
    successResult: 'render the audit entries and restore list context unchanged on close',
    errorResult: 'not applicable; empty history renders as an explicit empty section',
    refreshScope: 'no list refresh',
  },
  {
    id: 'ua-export-order-void',
    actorRoles: ['exportOrder.manager'],
    visibleWhen: 'actor has void permission and the order is not sailed, in post-sailing transit, completed, or cancelled',
    enabledWhen: 'the captured revision still permits voiding and no row mutation is pending',
    request: 'void the order after an explicit confirmation whose copy names the impact scope, using stable id, revision, and audit reason',
    successResult: 'mark the row voided, remove it from active queues, refresh queue counts, and keep the list context',
    errorResult: 'keep the confirmation open, preserve the row, and expose a retryable business error',
    refreshScope: 'current row and affected queue counts',
  },
  {
    id: 'ua-export-order-column-preferences',
    actorRoles: ['exportOrder.operator', 'exportOrder.cs', 'exportOrder.document', 'exportOrder.finance', 'exportOrder.manager', 'exportOrder.agent'],
    visibleWhen: 'the export-order workbench table is visible',
    enabledWhen: 'the table instance is ready and at least eight business columns remain selected',
    request: 'persist a versioned visible-field list plus movable business-column order in local workspace storage; no backend request',
    successResult: 'close the column panel, show success feedback, and apply the selected VXE column visibility and order immediately',
    errorResult: 'keep the column panel open, preserve the draft selection, and show a specific readiness or selection error',
    refreshScope: 'workbench table column visibility, order, and horizontal layout only',
  },
] as const);
