import { definePesdpPageSpec } from '@/design-system/pesdpPageSpec';

export const UA_EXPORT_ORDER_LIST_SPEC = definePesdpPageSpec({
  id: 'ui-acceptance-export-order-list',
  target: 'sellable-saas-grade',
  presentationTarget: 'daily-ops',
  archetype: 'list-workbench',
  input: {
    path: 'requirement',
    artifacts: ['docs/product/货代系统订单列表 Skill 黑盒测试需求.md'],
    unresolvedBusinessDecisions: [
      'production order API, real role/data-permission source, and workflow-transition backend do not exist in this repository',
      'the full create/edit order form page and the full order detail page are separate page contracts outside this black-box list-page test',
    ],
    recommendations: [
      'implement the list workbench, quick-view summary, and row/batch mutation overlays against local mock data with the repository uiState scenario mechanism; keep role contracts in featureContracts actorRoles',
      'keep the full edit form and full detail page as a visible boundary instead of rendering dead navigation entries',
    ],
  },
  list: {
    frame: 'standard-list-v1',
    profile: 'operations-workbench',
    commandSurface: 'workbench',
    tableTop: 'workbench-toolbar',
    selection: 'batch',
    workScope: 'required',
    statusQueues: 'required',
    views: {
      pageMode: 'none',
      pageModeCount: 0,
      workflowState: 'line-tabs',
      workflowStateCount: 12,
      workflowStatePlacement: 'workflow-row',
      workflowStateOverflow: 'local-scroll',
    },
  },
  business: {
    object: 'sea-export-order',
    primaryUser: 'freight-operator',
    userJob: 'locate-prioritize-and-progress-orders',
    primaryIdentity: ['orderNo'],
    keyState: ['orderStatus', 'exceptionStatus', 'riskFlags'],
    mainWorkingData: ['customerName', 'vesselVoyage', 'pol', 'pod', 'etd', 'closingTime', 'fileStatus', 'feeStatus', 'operator'],
    supportingData: ['eta', 'blNo', 'bookingNo', 'containerSummary', 'createdAt', 'updatedAt'],
  },
  pesdp: {
    professional: {
      decisions: [
        'Use sea-export order vocabulary, an eighteen-state main-flow status machine, ownership scope, and twelve operational queues; queues are a mutation-free workflow-state query dimension, not page navigation.',
        'Expose risk as first-class business truth: exception, missing-file, unconfirmed-fee, and overdue signals are independently recognizable on the same row without recoloring the row.',
      ],
      acceptance: [
        'Rendered columns expose order identity, main-flow status, exception/risk, route, ETD, and closing time without generic task wording.',
        'Ownership scope and the twelve processing queues share one mutation-free workflow row below query; saved-query commands stay with query actions, and risk queues (fee-unconfirmed, file-missing, exception) are visually distinguishable from normal queues.',
        'Queue switches change one query dimension, reset pagination and selection, and update queue counts and rows from the same result contract.',
        'Queue tabs show one concise label and count; risk details such as overdue state remain on the order row and in explicit filters.',
      ],
    },
    efficient: {
      decisions: [
        'Keep the unified identifier locate field (order no / BL no / booking no / container no without pre-selecting a type), daily narrow fields, queues, batch entry, and row next-action directly reachable.',
        'Batch operations pre-check mixed eligibility, report exact success/failure counts with reasons, keep failed rows selected, and offer a downloadable failure detail.',
      ],
      acceptance: [
        'At 1366x768 the command path stays compact, query actions sit with the query cluster, and the table owns the dominant share of usable height.',
        'Every mutation exposes a stable pending lock, blocks duplicate submission, preserves draft/selection/page context on failure, and refreshes only the affected rows, queue counts, and selection on success.',
        'Keyword query matches order no, BL no, booking no, and container no in one entry; Enter and the primary query button submit the same applied condition set.',
        'Saved query schemes support create, rename, delete, set-default, and reorder against local persistence without inventing a server contract.',
      ],
    },
    structured: {
      decisions: [
        'Use the shared standard-list frame: query, workflow state row, workbench table toolbar, feedback, and data in one stable order with one visible owner per fact.',
        'Row workflow verbs live in the row operation column and its overlays; the table toolbar owns create-output/batch contracts, selection context, utilities, and pagination.',
      ],
      acceptance: [
        'Totals appear in pagination and queue counts only; neither the toolbar nor any context strip repeats the total, active scope, active queue, or selected count outside the selection context.',
        'Advanced filter, saved-scheme management, status transition, assignment, exception marking, import, quick view, and column settings each have exactly one explicit overlay owner.',
        'Boolean conditions (has-exception, is-overdue) use direct three-state controls, never a Select simulating yes/no/all.',
      ],
    },
    dense: {
      decisions: [
        'Treat every permitted query field as belonging to exactly one user-configurable location: the aligned page surface or the grouped filter drawer; use one logical-unit grid with six minimum units, reserve two units for the query command group, and reject any placement exceeding two rows.',
        'Keep the global mini table density; more than twelve business columns ship with a default visible set of eight to twelve plus user column preferences persisted locally.',
      ],
      acceptance: [
        'At 1366, 1280, 1024 split, and wide viewports the query surface keeps the primary field/action baseline aligned until the supported split threshold, stays within two rows, the twelve queues overflow only inside their own lane, and the first table header plus first data row remain visible.',
        'The workbench toolbar command group and table surface share one horizontal start edge; no unowned leading notch appears beside the import/export actions.',
        'The workflow row transitions flush into the result toolbar, and toolbar controls have equal optical breathing room above and below before the table header.',
        'The workflow row has one shared bottom boundary; the state selector keeps its active ink without rendering a duplicate full-width navigation baseline.',
        'The advanced filter opens from the right at the shared D1 width, renders freight business groups with local counts and group reset, and keeps the native Drawer body as its only vertical scroll owner.',
        'The quick-view drawer keeps the list beside it visible, preserves query/page/selection context on close, and never becomes a top overlay.',
        'Long customer, vessel, port, and BL values truncate with hover access to the full value without breaking row height or layout.',
      ],
    },
    premium: {
      decisions: [
        'Keep GI and VXE native styling; derive quality from complete adverse states, the legal-transition matrix, mixed-eligibility batch handling, and a restrained row-action hierarchy: quick view and status transition direct, supporting work in More, void as the final confirmed danger group.',
        'Simulated concurrency uses a row revision: a stale revision on mutation is rejected with a refresh-and-compare message instead of silently overwriting.',
      ],
      acceptance: [
        'Illegal status transitions (cross-level, reverse, mutating a completed order) are business-rejected with the currently allowed next steps; cancellation and void require confirmation with impact copy.',
        'Permission denial renders as its own state and never impersonates a network error; sensitive profit fields are not rendered for unauthorized scenarios.',
        'Computed theme tokens, loading/slow/empty/permission/error/partial/long/extreme states, and 200% zoom are inspected on the real route.',
        'The route depends on no global selectors or theme-variable bridges that rewrite Arco or VXE internals.',
      ],
    },
  },
  surfaces: [
    { id: 'app-navigation', role: 'supporting', owns: ['module-navigation', 'route-identity'], implementation: 'arco' },
    { id: 'command', role: 'command', owns: ['query', 'saved-query-schemes', 'ownership-scope', 'status-queues'], primaryAction: 'ua-export-order-query', implementation: 'shared-pattern', whyArcoNotEnough: 'The routed list pages need one reusable owner for query, workflow, table, and overflow height relationships while Arco continues to own each surface.' },
    { id: 'advanced-query', role: 'supporting', owns: ['right-drawer-groups', 'advanced-query-draft', 'group-active-counts', 'group-reset', 'cancel-apply-state'], primaryAction: 'ua-export-order-query', implementation: 'arco' },
    { id: 'query-preferences', role: 'supporting', owns: ['page-and-drawer-placement', 'query-field-order', 'row-capacity', 'preference-persistence'], primaryAction: 'ua-export-order-query-preferences', implementation: 'shared-pattern', whyArcoNotEnough: 'Arco owns the drawer and controls; the shared pattern owns cross-list ordering, capacity validation, normalization, and preference persistence.' },
    { id: 'orders', role: 'data', owns: ['import', 'export', 'batch-actions', 'table-data', 'selection', 'batch-result', 'column-settings', 'pagination', 'total-count', 'table-feedback'], primaryAction: 'ua-export-order-import', implementation: 'shared-pattern', whyArcoNotEnough: 'Freight list grids require the shared VXE workbench wrapper and public fixed-column, overflow, loading, and preference configuration.' },
    { id: 'quick-view', role: 'detail', owns: ['order-summary', 'risk-summary', 'recent-nodes', 'fee-file-summary', 'recent-activity'], implementation: 'arco' },
    { id: 'action-overlays', role: 'supporting', owns: ['status-transition-modal', 'assign-modal', 'exception-modal', 'copy-confirm', 'void-confirm', 'scheme-manager'], implementation: 'arco' },
  ],
  query: {
    totalFields: 18,
    strategy: 'page-and-drawer',
    layout: 'semantic-grid-v1',
    visibleFields: ['keyword', 'customerName', 'pol', 'pod'],
    visibleFieldLayout: [
      { field: 'keyword', width: 'batch' },
      { field: 'customerName', width: 'standard' },
      { field: 'pol', width: 'standard' },
      { field: 'pod', width: 'standard' },
    ],
    layoutContract: { maxRows: 2, minimumUnits: 6, actionUnits: 2, capacityUnits: 10 },
    advancedFields: [
      'orderStatus',
      'exceptionStatus',
      'fileStatus',
      'feeStatus',
      'businessType',
      'operator',
      'carrier',
      'vesselVoyage',
      'etdRange',
      'closingRange',
      'createdRange',
      'updatedRange',
      'hasException',
      'isOverdue',
    ],
    personalization: {
      mode: 'page-and-drawer',
      pageRows: 2,
      minimumUnits: 6,
      actionUnits: 2,
      capacityUnits: 10,
      requiredPageFields: ['keyword'],
      ordering: 'page-global-drawer-grouped',
      persistence: 'local-workspace',
    },
  },
  table: {
    kind: 'workbench',
    rowBanding: 'striped',
    identityColumns: ['sequence', 'orderNo', 'orderStatus'],
    decisionColumns: ['customerName', 'businessType', 'vesselVoyage', 'pol', 'pod', 'etd', 'closingTime', 'fileStatus', 'feeStatus', 'exceptionStatus', 'riskFlags', 'operator'],
    supportingColumns: ['eta', 'blNo', 'bookingNo', 'containerSummary', 'createdAt', 'updatedAt'],
    fixed: ['checkbox', 'sequence', 'orderNo', 'operations'],
    densityReason: 'The global mini density keeps the repeated operational list compact and consistent across workbenches.',
    rowActions: { presentation: 'icon-tooltip', maxVisibleEntries: 3, directEntriesWithOverflow: 2, dangerPlacement: 'overflow-only' },
  },
  detail: {
    mode: 'display-first',
    focus: ['order-summary', 'risk-summary', 'next-action'],
    milestones: ['booked', 'space-released', 'customs-cleared', 'departed', 'arrived'],
    workspace: {
      archetype: 'reference-workspace',
      identityBand: {
        identity: ['orderNo', 'orderStatus'],
        keyFacts: ['customerName', 'vesselVoyage', 'pol', 'pod', 'etd', 'closingTime', 'operator'],
        decision: ['riskFlags', 'exceptionStatus', 'fileStatus', 'feeStatus'],
        actionOwner: 'none',
      },
      navigation: { mode: 'none', itemState: 'active-only' },
      usability: {
        identify: ['Operator identifies the order, its main-flow status, and its current risk within the first screen of the drawer.'],
        locateIssue: ['Operator locates which risk rule, missing file, or unconfirmed fee blocks the order.'],
        completeFrequentAction: ['Operator decides whether the full detail page is needed without losing list context.'],
      },
    },
    scroll: { verticalOwner: 'drawer-body', horizontalOverflow: 'table-only', stickyActionOwner: 'none' },
    modules: [
      {
        id: 'summary',
        kind: 'field-group',
        priority: 'core',
        mode: 'display',
        owns: ['orderNo', 'customerName', 'businessType', 'operator', 'pol', 'pod', 'etd', 'eta', 'closingTime', 'blNo', 'bookingNo', 'containerSummary'],
        metrics: [],
        actions: { module: [], table: [], row: [] },
        collapse: 'always-open',
        children: { kind: 'none' },
      },
      {
        id: 'risk',
        kind: 'exception',
        priority: 'core',
        mode: 'display',
        owns: ['riskFlags', 'exceptionStatus', 'exceptionSummary', 'fileStatus', 'feeStatus'],
        metrics: [],
        actions: { module: [], table: [], row: [] },
        collapse: 'always-open',
        children: { kind: 'none' },
      },
      {
        id: 'recent-nodes',
        kind: 'timeline',
        priority: 'supporting',
        mode: 'display',
        owns: ['recentNodes', 'nodeTime', 'nodeOperator'],
        metrics: [],
        actions: { module: [], table: [], row: [] },
        collapse: 'always-open',
        children: { kind: 'none' },
      },
      {
        id: 'recent-activity',
        kind: 'activity-log',
        priority: 'audit',
        mode: 'read-only',
        owns: ['recentLogs', 'logOperator', 'logTime', 'logAction'],
        metrics: [],
        actions: { module: [], table: [], row: [] },
        collapse: 'always-open',
        children: { kind: 'none' },
      },
    ],
  },
  actions: [
    { id: 'ua-export-order-query', scope: 'query', frequency: 'daily', risk: 'low', presentation: 'primary', contract: 'ua-export-order-query', successOwner: 'orders', failureOwner: 'orders' },
    { id: 'ua-export-order-query-preferences', scope: 'query', frequency: 'regular', risk: 'low', presentation: 'secondary', contract: 'ua-export-order-query-preferences', successOwner: 'query-preferences', failureOwner: 'query-preferences' },
    { id: 'ua-export-order-saved-schemes', scope: 'query', frequency: 'regular', risk: 'low', presentation: 'dropdown', contract: 'ua-export-order-saved-schemes', successOwner: 'command', failureOwner: 'command' },
    { id: 'ua-export-order-import', scope: 'command', frequency: 'regular', risk: 'medium', presentation: 'secondary', contract: 'ua-export-order-import', successOwner: 'orders', failureOwner: 'orders' },
    { id: 'ua-export-order-export', scope: 'command', frequency: 'regular', risk: 'low', presentation: 'dropdown', contract: 'ua-export-order-export', successOwner: 'orders', failureOwner: 'orders' },
    { id: 'ua-export-order-batch', scope: 'selection', frequency: 'regular', risk: 'medium', presentation: 'dropdown', contract: 'ua-export-order-batch', successOwner: 'orders', failureOwner: 'orders' },
    { id: 'ua-export-order-quick-view', scope: 'row', frequency: 'daily', risk: 'low', presentation: 'row-action', contract: 'ua-export-order-quick-view', successOwner: 'quick-view', failureOwner: 'orders' },
    { id: 'ua-export-order-status-transition', scope: 'row', frequency: 'regular', risk: 'medium', presentation: 'row-action', contract: 'ua-export-order-status-transition', successOwner: 'orders', failureOwner: 'action-overlays' },
    { id: 'ua-export-order-assign', scope: 'row', frequency: 'regular', risk: 'low', presentation: 'dropdown', contract: 'ua-export-order-assign', successOwner: 'orders', failureOwner: 'action-overlays' },
    { id: 'ua-export-order-mark-exception', scope: 'row', frequency: 'regular', risk: 'medium', presentation: 'dropdown', contract: 'ua-export-order-mark-exception', successOwner: 'orders', failureOwner: 'action-overlays' },
    { id: 'ua-export-order-generate-fee', scope: 'row', frequency: 'regular', risk: 'low', presentation: 'dropdown', contract: 'ua-export-order-generate-fee', successOwner: 'orders', failureOwner: 'orders' },
    { id: 'ua-export-order-notify', scope: 'row', frequency: 'regular', risk: 'low', presentation: 'dropdown', contract: 'ua-export-order-notify', successOwner: 'orders', failureOwner: 'orders' },
    { id: 'ua-export-order-upload-file', scope: 'row', frequency: 'regular', risk: 'low', presentation: 'dropdown', contract: 'ua-export-order-upload-file', successOwner: 'orders', failureOwner: 'orders' },
    { id: 'ua-export-order-copy', scope: 'row', frequency: 'rare', risk: 'low', presentation: 'dropdown', contract: 'ua-export-order-copy', successOwner: 'orders', failureOwner: 'orders' },
    { id: 'ua-export-order-view-log', scope: 'row', frequency: 'rare', risk: 'low', presentation: 'dropdown', contract: 'ua-export-order-view-log', successOwner: 'quick-view', failureOwner: 'orders' },
    { id: 'ua-export-order-void', scope: 'row', frequency: 'rare', risk: 'high', presentation: 'dropdown', contract: 'ua-export-order-void', successOwner: 'orders', failureOwner: 'orders' },
    { id: 'ua-export-order-column-preferences', scope: 'data-utilities', frequency: 'regular', risk: 'low', presentation: 'text', contract: 'ua-export-order-column-preferences', successOwner: 'orders', failureOwner: 'orders' },
  ],
  states: ['loading', 'slow', 'empty', 'no-permission', 'network-error', 'long-text', 'extreme-value', 'partial-failure', 'stale-revision', 'success'],
  responsive: { release: ['1366x768', '1280x720'], split: '1024x768', wide: '1920x1080' },
  accessibility: {
    keyboard: ['Reach and operate query, schemes, queues, table utilities, row actions, pagination, and every opened overlay in workflow order.'],
    naming: ['Every icon-only command and state-changing control exposes a business-specific accessible name.'],
    zoom: '200%',
  },
  authorities: ['list-page.md', 'filter-layout.md', 'table.md', 'actions.md', 'feature-delivery-contract.md', 'feedback.md', 'permissions.md', 'modal.md', 'overlay-dimensions.md', 'upload.md', 'responsive.md'],
  verification: ['node scripts/check-spec.js', 'npm run build', 'real-route viewport and state matrix'],
});
