import type { NotificationRecord } from './types';

export const mockNotifications: NotificationRecord[] = [
  {
    Id: '1',
    type: '内部通知',
    subject: '2026年端午节放假安排',
    content: '根据国家法定节假日安排，2026年端午节放假时间为6月19日至6月21日...',
    files: [
      { uid: 'f1', name: '放假通知.png', url: '#' },
      { uid: 'f2', name: '值班表.xlsx', url: '#' },
    ],
    status: 'published',
    lastPublishTime: '2026-05-28 10:30:00',
    targetType: 'all',
    targetLabel: '全员通知',
    effectivePeriod: '否',
    creator: 'admin',
    lastEditTime: '2026-05-28 10:25:00',
  },
  {
    Id: '2',
    type: '内部通知',
    subject: '系统升级维护公告',
    content: '计划于2026年6月5日凌晨2:00-6:00进行系统升级维护，期间系统将暂停服务...',
    files: [{ uid: 'f3', name: '升级说明.pptx', url: '#' }],
    status: 'draft',
    lastPublishTime: '',
    targetType: 'custom',
    targetLabel: '自定义通知',
    effectivePeriod: '是',
    creator: 'admin',
    lastEditTime: '2026-06-01 14:20:00',
  },
  {
    Id: '3',
    type: '内部通知',
    subject: '新员工入职培训通知',
    content: '请各部门安排新入职员工参加6月10日举行的入职培训...',
    files: [],
    status: 'pending',
    lastPublishTime: '',
    targetType: 'custom',
    targetLabel: '自定义通知',
    effectivePeriod: '否',
    creator: 'zhangsan',
    lastEditTime: '2026-06-02 09:15:00',
  },
  {
    Id: '4',
    type: '内部通知',
    subject: '五一劳动节放假通知',
    content: '2026年五一劳动节放假安排已发布，请各部门做好值班安排...',
    files: [{ uid: 'f4', name: '值班checklist.checklist', url: '#' }],
    status: 'expired',
    lastPublishTime: '2026-04-25 16:00:00',
    targetType: 'all',
    targetLabel: '全员通知',
    effectivePeriod: '是',
    creator: 'admin',
    lastEditTime: '2026-04-25 15:50:00',
  },
  {
    Id: '5',
    type: '内部通知',
    subject: '年度绩效考核启动',
    content: '2026年度绩效考核工作正式启动，请各部门于6月30日前完成自评...',
    files: [],
    status: 'published',
    lastPublishTime: '2026-06-01 08:00:00',
    targetType: 'custom',
    targetLabel: '自定义通知',
    effectivePeriod: '否',
    creator: 'lisi',
    lastEditTime: '2026-06-01 07:55:00',
  },
  {
    Id: '6',
    type: '内部通知',
    subject: '办公区域装修通知',
    content: '三楼办公区域将于下周一开始装修，请相关部门提前做好准备...',
    files: [],
    status: 'cancelled',
    lastPublishTime: '2026-05-10 11:00:00',
    targetType: 'all',
    targetLabel: '全员通知',
    effectivePeriod: '否',
    creator: 'admin',
    lastEditTime: '2026-05-12 09:00:00',
  },
];
